import 'dart:ui';
import 'local_storage_service.dart';

class AppLanguage {
  final String code;
  final String label;

  const AppLanguage({required this.code, required this.label});

  Locale get locale => Locale(code);
}

class LanguageService {
  LanguageService(this._storage);

  final LocalStorageService _storage;

  static const supported = <AppLanguage>[
    AppLanguage(code: 'en', label: 'English'),
    AppLanguage(code: 'ar', label: 'العربية'),
  ];

  Future<AppLanguage> loadLanguage() async {
    final saved = await _storage.getLocaleCode();
    final found = supported.where((e) => e.code == saved).toList();

    if (found.isNotEmpty) return found.first;
    return supported.first;
  }

  Future<void> setLanguage(String code) async {
    await _storage.setLocaleCode(code);
  }

  static final Map<String, Map<String, String>> translations = {
    'en': {
      'login': 'Login',
      'signUp': 'Sign Up',
      'email': 'Email',
      'password': 'Password',
      'confirmPassword': 'Confirm Password',
      'fullName': 'Full Name',
      'forgetPassword': 'Forget Password?',
      'dontHaveAccount': "Don't have an account? ",
      'youHaveAccount': 'You have an account? ',
      'or': 'or',
      'english': 'English',
      'arabic': 'Arabic',
      'pleaseWait': 'Please wait...',
      'pleaseFillAllFields': 'Please fill all fields',
      'passwordsDoNotMatch': 'Passwords do not match',
      'passwordLength': 'Password must be at least 6 characters',
      'accountCreated': 'Account created successfully!',
      'passwordResetTitle': 'Password Reset',
      'passwordResetBody':
          'A reset email has been sent to your address.\nPlease check your inbox and follow the instructions.',
      'ok': 'OK',
      'send': 'Send',
      'backToLogin': 'Back to Login',
      'skip': 'Skip',
      'next': 'Next',
      'goToHome': 'Go To Home',
      'findPerfectWorkspace': 'Find your perfect workspace',
      'bookStudySpaces':
          'Book work and study spaces with clear\nprices, real insights, and flexible plans.',
      'clearInfoBeforeBook': 'Clear info before you book',
      'clearInfoSubtitle': 'Price, rating, internet quality, and noise level.',
      'whyMashtak': 'Why Mashtak',
      'bookWithConfidence': 'Book with confidence',
      'bookWithConfidenceSubtitle': 'Requests are approved before payment.',
      'smartSuggestions': 'Smart suggestions',
      'smartSuggestionsSubtitle':
          'AI highlights the best spaces for your goal.',
      'whatAreYouBookingFor': 'What are you booking for?',
      'selectAllThatApply':
          "Select all that apply. We'll tailor\nspaces to your needs.",
      'mainPurpose': 'Main purpose',
      'selectMultiple': 'Select multiple',
      'whatMattersMost': 'What matters most?',
      'whatMattersOptional': 'Optional â€” helps us rank results better.',
      'youllSeeInsightsLike': "You'll see insights like",
      'insightBestStudy': 'Best for study',
      'insightQuietInternet': 'Quiet + strong internet',
      'insightWeeklySaves': 'Weekly saves more',
      'aiWillUseYourChoices': 'AI will use your choices',
      'aiSubtitle': 'Smarter suggestions + review summaries\n(not a chatbot).',
      'aiFootnote': 'You can change these later in Settings.',
      'purposeStudy': 'Study',
      'purposeDeepFocus': 'Deep Focus',
      'purposeMeetings': 'Meetings',
      'purposeTeamWork': 'Team Work',
      'purposeCallsInterviews': 'Calls / Interviews',
      'purposeCreative': 'Creative',
      'matterQuiet': 'Quiet',
      'matterFastWifi': 'Fast Wi-Fi',
      'matterBudgetFriendly': 'Budget friendly',
      'stayUpdated': 'Stay updated',
      'chooseAlerts':
          'Choose the alerts you want.\nYou can change them anytime.',
      'bookingAlerts': 'Booking alerts',
      'bookingApproved': 'Booking approved',
      'bookingApprovedSubtitle': 'When a space confirms your request.',
      'bookingRejected': 'Booking rejected',
      'bookingRejectedSubtitle': 'So you can quickly pick another option.',
      'reminderBeforeBooking': 'Reminder before booking',
      'reminderBeforeBookingSubtitle':
          'A quick reminder before your reserved time.',
      'reminderTiming': 'Reminder timing',
      'optionalLabel': '(Optional)',
      'notificationsHelp': 'Notifications help you trust bookings',
      'notificationsSubtitle':
          'Get approvals, rejections, and reminders\nright on time.',
      'notificationsFootnote':
          "Tip: You'll still see booking status inside the Bookings tab.",
      'timing30min': '30 min',
      'timing1hour': '1 hour',
      'timingSameDay': 'Same day (9 AM)',
      'navHome': 'Home',
      'navBookings': 'Bookings',
      'navProfile': 'Profile',
      'navSettings': 'Settings',
      'homeTitle': 'Home',
      'searchHint': 'Search',
      'aiConcierge': 'AI Concierge',
      'catNearly': 'Nearly',
      'catNewSuggestion': 'New Suggestion',
      'catPrivateOffice': 'Private Office',
      'forYou': 'For You',
      'noSpacesYet': 'No spaces yet',
      'insightsSection': 'Insights',
      'noInsightsYet': 'No insights yet',
      'view': 'View',
      'insBestForYou': 'Best For You',
      'insBestForYouSub': 'Find the space that matches your goal.',
      'insExclusiveDeals': 'Exclusive Deals',
      'insExclusiveDealsSub': 'Exclusive deals on top spaces.',
      'insWeeklyPlan': 'Weekly Plan',
      'insWeeklyPlanSub': 'Unlock your productivity hub.',
      'insMeetingChecklist': 'Meeting-ready checklist',
      'insMeetingChecklistSub': "Don't miss the essentials.",
      'offersPageTitle': 'Offers',
      'offersTopDeals': 'Top Deals',
      'offersEmpty': 'No offers available right now.',
      'upcomingBookings': 'Your Upcoming Bookings',
      'pastBookings': 'Past Bookings',
      'cancelledBookings': 'Cancelled Bookings',
      'noBookingsYet': 'No bookings yet',
      'cancel': 'Cancel',
      'rebook': 'Rebook',
      'manageBooking': 'Manage booking',
      'bookingStatusUpcoming': 'Upcoming',
      'bookingStatusCompleted': 'Completed',
      'bookingStatusCancelled': 'Cancelled',
      'bookingIdLabel': 'Booking ID:',
      'pricePerDay': '/day',
      'bookingInfoLabel': 'Booking info',
      'bookingDateLabel': 'Date',
      'bookingTimeLabel': 'Time',
      'bookingNotesLabel': 'Notes',
      'bookingTotalLabel': 'Total',
      'bookingDetailsTitle': 'Booking Details',
      'profileTitle': 'Profile',
      'saved': 'Saved',
      'reviews': 'Reviews',
      'personalInfo': 'Personal Info',
      'yourUsage': 'Your usage',
      'paymentsReceipts': 'Payments & Receipts',
      'paymentDetails': 'Payment Details',
      'reviewsRatings': 'Reviews & Ratings',
      'savedSpaces': 'Saved Spaces',
      'logOut': 'Log Out',
      'settingsTitle': 'Settings',
      'preferences': 'Preferences',
      'workspacePreferences': 'Workspace preferences',
      'workspacePreferencesSub': 'Study, work, meetings',
      'location': 'Location',
      'locationSub': 'Nearby & map search',
      'notifications': 'Notifications',
      'notificationsSub': 'Booking & offers',
      'appLanguage': 'Language',
      'appLanguageSub': 'English / Arabic',
      'chooseLanguage': 'Choose language',
      'close': 'Close',
      'support': 'Support',
      'helpSupport': 'Help & support',
      'helpSupportSub': 'FAQs, contact us',
      'aboutMashtak': 'About Mashtak',
      'aboutMashatakSub': 'Version, terms, privacy',
      'retry': 'Retry',
      'notificationsPageTitle': 'Notifications',
      'notificationsPageHeader': 'Updates for you',
      'notificationsPageSubtitle':
          'Booking status, reminders, and smart plan tips.',
      'notifGroupToday': 'TODAY',
      'notifGroupEarlier': 'EARLIER',
      'notifItemTitleApproved': 'Booking Approved! ًںژ‰',
      'notifItemSubApproved': 'Your booking has been confirmed.',
      'notifItemTitleRejected': 'Booking Rejected',
      'notifItemSubRejected':
          'Your request could not be accepted. Try another space.',
      'notifItemTitleReminder': 'Booking Reminder âڈ°',
      'notifItemSubReminder': 'Your session is starting soon. Get ready!',
      'notifItemTitleOffer': 'New Weekly Deal ًں”¥',
      'notifItemSubOffer': 'Save more with the weekly pass. Limited spots!',
      'notifSettingsTitle': 'Notification Settings',
      'notifSettingsStayInControl': 'Stay in control',
      'notifSettingsChooseUpdates': 'Choose which updates you want to receive.',
      'notifSettingsBookingReminder': 'Booking reminder',
      'notifSettingsReminderSub': 'Reminder before your reserved time.',
      'notifSettingsOffersPlans': 'Offers & plans',
      'notifSettingsOfferSuggestion': 'Offer / plan suggestion',
      'notifSettingsOfferSub': 'Weekly plan could save you money.',
      'save': 'Save',
      'usagePageTitle': 'Your Usage',
      'usageBasedOn': 'Based on your last 30 days',
      'usagePlanOptimizer': 'Plan Optimizer',
      'usageComparePlans': 'Compare plans',
      'usageRecommendation': 'Recommendation',
      'usageApplyPlan': 'Apply Plan',
      'usagePlanApplied': 'Plan applied successfully!',
      'reviewsPageTitle': 'Reviews & Ratings',
      'reviewsFilter': 'Filter',
      'reviewsAll': 'All',
      'reviewsMyReviews': 'My reviews',
      'reviewsMostRecent': 'Most recent',
      'reviewsRecent': 'Recent reviews',
      'reviewsTip': 'Tip: You can edit your reviews from Space',
      'reviewsOverall': 'Overall',
      'reviewsBasedOn': 'Based on',
      'reviewsBasedOnSuffix': 'reviews',
      'weeklyPlanTitle': 'Weekly Plan',
      'weeklyPlanSaveMore': 'Save more with weekly access',
      'weeklyPlanSubtitle': 'Best option for frequent visits and focused work',
      'weeklyPlanWhatYouGet': 'What you get',
      'weeklyPlanActivate': 'Activate plan',
      'weeklyPlanActivated': 'Plan activated successfully!',
      'bookingStatusPageTitle': 'Booking status',
      'bookingStatusHeader': 'Booking request',
      'bookingStatusPullRefresh': 'Pull to refresh for latest status',
      'bookingStatusApprovedBanner':
          'Booking is approved. Please proceed to payment.',
      'bookingStatusRefreshBtn': 'Refresh status',
      'bookingStatusCancelBtn': 'Cancel request',
      'bookingStatusGoPaymentBtn': 'Go to payment',
      'bookingStatusPaidMsg':
          'Paid successfully. You can view booking details from your bookings list.',
      'timelineProgress': 'Progress',
      'timelineRequestSent': 'Request sent',
      'timelineRequestSentSub': 'We received your request',
      'timelineUnderReview': 'Under review',
      'timelineUnderReviewSub': 'Checking availability',
      'timelineUnderReviewWaiting': 'Waiting to start review',
      'timelineUnderReviewCompleted': 'Completed',
      'timelineApproved': 'Approved',
      'timelineApprovedSub': 'Proceed to payment',
      'timelinePaymentCompleted': 'Payment completed',
      'timelineCancelled': 'Cancelled',
      'timelineCancelledSub': 'Request cancelled by user',
      'timelineRejected': 'Rejected',
      'timelineRejectedSub': 'Request rejected',
      'summaryRequestId': 'Request ID',
      'summaryStart': 'Start',
      'summaryDuration': 'Duration',
      'summaryPurpose': 'Purpose',
      'summaryOffer': 'Offer',
      'summaryTotal': 'Total',
      'statusPending': 'Pending',
      'statusUnderReview': 'Under review',
      'statusApproved': 'Approved',
      'statusRejected': 'Rejected',
      'statusCancelled': 'Cancelled',
      'statusPaid': 'Paid',
      'statusLoading': 'Loading',
      'kpiTodayTitle': 'Today Bookings',
      'kpiTodayDelta': 'bookings today',
      'kpiPendingTitle': 'Pending Requests',
      'kpiNeedsReview': 'Needs review',
      'kpiAllClear': 'All clear',
      'kpiSpacesTitle': 'Active Spaces',
      'kpiSpacesDelta': 'total spaces',
      'kpiRevenueTitle': 'Weekly Revenue',
      'kpiRevenueDelta': 'last 7 days',
      'activityRequested': 'requested booking at',
      'activityApproved': 'booking approved for',
      'activityPayment': 'submitted payment for',
      'activityConfirmed': 'confirmed booking at',
      'activityCancelled': 'booking cancelled at',
      'activityBooked': 'booked',
      'timeJustNow': 'just now',
      'timeMinAgo': 'min ago',
      'timeHoursAgo': 'h ago',
      'timeDaysAgo': 'd ago',
      'mapShowAll': 'Show All',
      'mapNearby': 'Nearby',
      'mapNoResults': 'No results in this area.',
      'mapTitle': 'Explore Spaces on Map',
      'adminTabHome': 'Home',
      'adminTabBookings': 'Bookings',
      'adminTabUsers': 'Users',
      'adminTabSubAdmins': 'Sub Admins',
      'adminTabSettings': 'Settings',
      'adminDashboardTitle': 'Admin Dashboard',
      'adminDashboardSubtitle': 'Manage your coworking spaces',
      'adminSelectedSpace': 'Selected Space',
      'adminSelectSpace': 'Select Space',
      'adminRecentActivity': 'Recent Activity',
      'adminMore': 'More',
      'adminNoRecentActivity': 'No recent activity',
      'adminQuickActions': 'Quick Actions',
      'adminViewRequests': 'View Requests',
      'adminManageCalendar': 'Manage Calendar',
      'adminCreateOffer': 'Create Offer',
      'adminViewReviews': 'View Reviews',
      'adminManageSubAdmins': 'Manage Sub Admins',
      'adminManage': 'Manage',
      'adminHide': 'Hide',
      'adminHidden': 'Hidden',
      'adminAvailable': 'Available',
      'adminAvailability': 'Availability',
      'adminImage': 'Image',
      'adminDelete': 'Delete',
      'adminRetry': 'Retry',
      'adminBack': 'Back',
      'adminNone': 'None',
      'adminConfirm': 'Confirm',
      'adminReject': 'Reject',
      'adminSaving': 'Saving...',
      'subAdminsTitle': 'Sub Admins',
      'subAdminsSubtitle': 'Manage restricted admin accounts',
      'subAdminsNoItems': 'No sub admins yet. Tap + to create one.',
      'subAdminCreate': 'Create Sub Admin',
      'subAdminEdit': 'Edit Sub Admin',
      'subAdminRemove': 'Remove Sub Admin',
      'subAdminAssignSpaces': 'Assign Spaces',
      'subAdminAssignedSpaces': 'Assigned Spaces',
      'subAdminNoSpaces': 'No spaces assigned',
      'subAdminNameLabel': 'Name',
      'subAdminNameHint': 'Full name',
      'subAdminPasswordHint': 'Min 6 characters',
      'subAdminFillAll': 'Please fill all fields',
      'adminBookingRequests': 'Booking Requests',
      'adminBookingRequestsSubtitle': 'Manage booking requests',
      'adminTabPending': 'Pending',
      'adminTabApproved': 'Approved',
      'adminTabCanceled': 'Canceled',
      'adminTabPayReview': 'Pay Review',
      'adminBookingDetails': 'Booking Details',
      'adminCustomerInfo': 'Customer Information',
      'adminBookingInfo': 'Booking Information',
      'adminCancelBooking': 'Cancel Booking',
      'adminCancelReason': 'Please provide a reason for cancellation',
      'adminCancelReasonHint': 'Enter cancellation reason...',
      'adminConfirmCancel': 'Confirm Cancel',
      'adminConfirmBooking': 'Confirm Booking',
      'adminField': 'Field',
      'adminDetailsCol': 'Details',
      'adminKvSpace': 'Space',
      'adminKvAddress': 'Address',
      'adminKvDate': 'Date',
      'adminKvTime': 'Time',
      'adminKvDuration': 'Duration',
      'adminKvPlan': 'Plan',
      'adminKvPrice': 'Price',
      'adminKvTotal': 'Total',
      'adminMySpaces': 'My Spaces',
      'adminMySpacesSubtitle': 'Manage your listed spaces',
      'adminDeleteSpace': 'Delete Space',
      'adminDeleteSpaceConfirm':
          'Are you sure you want to delete this space? This action cannot be undone.',
      'adminAddSpace': 'Add Space',
      'adminEditSpace': 'Edit Space',
      'adminUpdateSpaceInfo': 'Update your space info',
      'adminSpaceName': 'Name',
      'adminSpaceNameHint': 'Space name',
      'adminAddressLabel': 'Address (text)',
      'adminAddressHint': 'e.g. 12 King St, Downtown',
      'adminTotalSeats': 'Total Seats',
      'adminSeatsHint': 'e.g. 20',
      'adminSeats': 'seats',
      'adminSpaceAdmin': 'Space Admin',
      'adminAssignSubAdmin': 'Assign Sub Admin',
      'adminSelectSubAdmin': 'Select sub admin (optional)',
      'adminFailedLoad': 'Failed to load space',
      'adminPaymentReview': 'Payment Review',
      'adminPaymentReviewSubtitle': 'Verify incoming payments',
      'adminNoPaymentsPending': 'No payments pending review',
      'adminUnderReview': 'Under Review',
      'adminPaymentUser': 'User',
      'adminPaymentAmount': 'Amount',
      'adminPaymentMethod': 'Method',
      'adminPaymentPaidAt': 'Paid at',
      'adminPaymentReceipt': 'Payment Receipt',
      'adminViewReceipt': 'View Receipt',
      'adminNoReceipt': 'No receipt uploaded',
      'adminPaymentMethodsTitle': 'Available Payment Methods',
      'adminPaymentMethodsSubtitle':
          'Select methods and enter account details for each',
      'adminPaymentAccountDetails': 'Account Details',
      'adminPaymentAccountDetailsHint': 'Account number, IBAN, owner name...',
      'adminSelectPaymentMethod': 'Select payment method...',
      'adminAddPaymentMethod': 'Add',
      'adminPaymentAccountName': 'Account Holder Name',
      'adminPaymentAccountNameHint': 'Full name of account owner',
      'adminPaymentPhone': 'Phone Number',
      'adminPaymentCardNote':
          'Card payment is processed through the space\'s point-of-sale terminal upon arrival.',
      'paymentMethodTitle': 'Payment Method',
      'paymentMethodDetails': 'Transfer Details',
      'paymentUploadReceipt': 'Upload Payment Receipt',
      'paymentReceiptUploaded': 'Receipt Uploaded',
      'paymentChangeReceipt': 'Change Receipt',
      'paymentCompleteBtn': 'Complete Payment',
      'paymentReceiptRequired': 'Please upload the payment receipt first',
      'paymentNoMethods': 'No payment methods available for this space',
      'paymentCardDetails': 'Card Details',
      'paymentCardNumber': 'Card Number',
      'paymentCardExpiry': 'Expiry Date',
      'paymentCardCvv': 'CVV',
      'paymentCardHolder': 'Card Holder Name',
      'adminSettings': 'Settings',
      'adminAnalytics': 'Analytics',
      'adminPerformance': 'Performance',
      'adminPerformanceSubtitle': 'KPIs & weekly bookings',
      'adminTopSpaces': 'Top Spaces',
      'adminTopSpacesSubtitle': 'Top performing + export',
      'adminAdminActions': 'Admin actions',
      'adminViewRequestsSubtitle': 'Pending/approved/canceled',
      'adminManageCalendarSubtitle': 'Closures & special hours',
      'adminOffersManagement': 'Offers Management',
      'adminOffersManagementSubtitle': 'Discounts & packages',
      'adminReviewsReports': 'Reviews & Reports',
      'adminReviewsReportsSubtitle': 'Moderation & replies',
      'adminAccount': 'Account',
      'adminLogout': 'Logout',
      'adminLogoutSubtitle': 'Sign out of admin account',
      'adminUsersTitle': 'Users',
      'adminUsersSubtitle': 'Search and manage users',
      'adminSearchUsers': 'Search users...',
      'adminFilterAll': 'All',
      'adminFilterNew': 'New',
      'adminFilterFlagged': 'Flagged',
      'apple': 'Apple login coming soon',
      'enterEmail': 'Enter your email and we will send you instructions.',
      'forgotPassword': 'Forgot Password',
    },
    'ar': {
      'login': 'تسجيل الدخول',
      'signUp': 'إنشاء حساب',
      'email': 'البريد الإلكتروني',
      'password': 'كلمة المرور',
      'confirmPassword': 'تأكيد كلمة المرور',
      'fullName': 'الاسم الكامل',
      'forgetPassword': 'نسيت كلمة المرور؟',
      'dontHaveAccount': 'ليس لديك حساب؟ ',
      'youHaveAccount': 'لديك حساب؟ ',
      'or': 'أو',
      'english': 'الإنجليزية',
      'arabic': 'العربية',
      'pleaseWait': 'يرجى الانتظار...',
      'pleaseFillAllFields': 'يرجى تعبئة جميع الحقول',
      'passwordsDoNotMatch': 'كلمات المرور غير متطابقة',
      'passwordLength': 'كلمة المرور يجب أن تكون 6 أحرف على الأقل',
      'accountCreated': 'تم إنشاء الحساب بنجاح',
      'passwordResetTitle': 'إعادة تعيين كلمة المرور',
      'passwordResetBody':
          'تم إرسال رابط لإعادة التعيين إلى بريدك، تحقق منه واتبع التعليمات.',
      'ok': 'حسناً',
      'send': 'إرسال',
      'backToLogin': 'العودة لتسجيل الدخول',
      'skip': 'تخطي',
      'next': 'التالي',
      'goToHome': 'الدخول للرئيسية',
      'findPerfectWorkspace': 'اعثر على مساحة العمل المناسبة',
      'bookStudySpaces':
          'احجز أماكن للعمل والدراسة بسهولة وبمعلومات واضحة وخيارات مرنة.',
      'clearInfoBeforeBook': 'معلومات واضحة قبل الحجز',
      'clearInfoSubtitle': 'السعر، التقييم، جودة الإنترنت ومستوى الهدوء.',
      'whyMashtak': 'لماذا مساحتك',
      'bookWithConfidence': 'احجز بثقة',
      'bookWithConfidenceSubtitle': 'يتم تأكيد الطلب قبل الدفع.',
      'smartSuggestions': 'اقتراحات ذكية',
      'smartSuggestionsSubtitle': 'نرشح لك أفضل الأماكن حسب هدفك.',
      'whatAreYouBookingFor': 'ما الهدف من الحجز؟',
      'selectAllThatApply': 'اختر ما يناسبك وسنرشح لك الأفضل.',
      'mainPurpose': 'الغرض الرئيسي',
      'selectMultiple': 'يمكن اختيار أكثر من خيار',
      'whatMattersMost': 'ما الأهم بالنسبة لك؟',
      'whatMattersOptional': 'اختياري لتحسين النتائج',
      'youllSeeInsightsLike': 'ستظهر لك نتائج مثل',
      'insightBestStudy': 'مناسب للدراسة',
      'insightQuietInternet': 'هادئ + إنترنت قوي',
      'insightWeeklySaves': 'الأسبوعي أوفر',
      'aiWillUseYourChoices': 'سيتم استخدام اختياراتك لتحسين النتائج',
      'aiSubtitle': 'اقتراحات أذكى مبنية على تقييمات المستخدمين',
      'aiFootnote': 'يمكنك تعديلها لاحقاً من الإعدادات',
      'purposeStudy': 'دراسة',
      'purposeDeepFocus': 'تركيز',
      'purposeMeetings': 'اجتماعات',
      'purposeTeamWork': 'عمل جماعي',
      'purposeCallsInterviews': 'مكالمات / مقابلات',
      'purposeCreative': 'إبداع',
      'matterQuiet': 'هدوء',
      'matterFastWifi': 'إنترنت سريع',
      'matterBudgetFriendly': 'سعر مناسب',
      'stayUpdated': 'ابقَ على اطلاع',
      'chooseAlerts': 'اختر الإشعارات التي تريدها',
      'bookingAlerts': 'تنبيهات الحجز',
      'bookingApproved': 'تم قبول الحجز',
      'bookingApprovedSubtitle': 'تم تأكيد طلبك',
      'bookingRejected': 'تم رفض الحجز',
      'bookingRejectedSubtitle': 'يمكنك اختيار مكان آخر',
      'reminderBeforeBooking': 'تذكير قبل الموعد',
      'reminderBeforeBookingSubtitle': 'سيتم تذكيرك قبل الحجز',
      'reminderTiming': 'وقت التذكير',
      'optionalLabel': 'اختياري',
      'notificationsHelp': 'الإشعارات تساعدك تتابع حجوزاتك',
      'notificationsSubtitle': 'تصلك التحديثات فوراً',
      'notificationsFootnote': 'يمكنك متابعة الحالة أيضاً من صفحة الحجوزات',
      'timing30min': '30 دقيقة',
      'timing1hour': 'ساعة',
      'timingSameDay': 'نفس اليوم',
      'navHome': 'الرئيسية',
      'navBookings': 'الحجوزات',
      'navProfile': 'الملف الشخصي',
      'navSettings': 'الإعدادات',
      'homeTitle': 'الرئيسية',
      'searchHint': 'ابحث...',
      'aiConcierge': 'المساعد الذكي',
      'catNearly': 'قريب',
      'catNewSuggestion': 'اقتراح جديد',
      'catPrivateOffice': 'مكتب خاص',
      'forYou': 'مناسب لك',
      'noSpacesYet': 'لا توجد مساحات حالياً',
      'insightsSection': 'اقتراحات',
      'noInsightsYet': 'لا توجد بيانات بعد',
      'view': 'عرض',
      'upcomingBookings': 'الحجوزات القادمة',
      'pastBookings': 'الحجوزات السابقة',
      'cancelledBookings': 'الملغاة',
      'noBookingsYet': 'لا يوجد حجوزات',
      'cancel': 'إلغاء',
      'rebook': 'إعادة الحجز',
      'manageBooking': 'إدارة الحجز',
      'bookingStatusUpcoming': 'قادمة',
      'bookingStatusCompleted': 'مكتملة',
      'bookingStatusCancelled': 'ملغية',
      'bookingIdLabel': 'رقم الحجز',
      'pricePerDay': '/يوم',
      'bookingInfoLabel': 'معلومات الحجز',
      'bookingDateLabel': 'التاريخ',
      'bookingTimeLabel': 'الوقت',
      'bookingNotesLabel': 'ملاحظات',
      'bookingTotalLabel': 'الإجمالي',
      'bookingDetailsTitle': 'تفاصيل الحجز',
      'profileTitle': 'الملف الشخصي',
      'saved': 'المحفوظات',
      'reviews': 'التقييمات',
      'personalInfo': 'المعلومات الشخصية',
      'yourUsage': 'استخدامك',
      'paymentsReceipts': 'الدفع والفواتير',
      'paymentDetails': 'تفاصيل الدفع',
      'reviewsRatings': 'التقييمات',
      'savedSpaces': 'المساحات المحفوظة',
      'logOut': 'تسجيل الخروج',
      'settingsTitle': 'الإعدادات',
      'preferences': 'التفضيلات',
      'workspacePreferences': 'تفضيلات المساحة',
      'workspacePreferencesSub': 'دراسة، عمل، اجتماعات',
      'location': 'الموقع',
      'locationSub': 'بحث قريب وخريطة',
      'notifications': 'الإشعارات',
      'notificationsSub': 'الحجوزات والعروض',
      'appLanguage': 'اللغة',
      'appLanguageSub': 'عربي / إنجليزي',
      'chooseLanguage': 'اختر اللغة',
      'close': 'إغلاق',
      'support': 'الدعم',
      'helpSupport': 'مساعدة ودعم',
      'helpSupportSub': 'الأسئلة الشائعة والتواصل',
      'aboutMashtak': 'حول التطبيق',
      'aboutMashatakSub': 'الإصدار والشروط',
      'retry': 'إعادة المحاولة',
      'statusPending': 'قيد الانتظار',
      'statusUnderReview': 'قيد المراجعة',
      'statusApproved': 'تم القبول',
      'statusRejected': 'مرفوض',
      'statusCancelled': 'ملغي',
      'statusPaid': 'مدفوع',
      'statusLoading': 'جاري التحميل',
      'adminDashboardTitle': 'لوحة التحكم',
      'adminDashboardSubtitle': 'إدارة المساحات',
      'adminRecentActivity': 'النشاط الأخير',
      'adminQuickActions': 'إجراءات سريعة',
      'adminViewRequests': 'عرض الطلبات',
      'adminManageCalendar': 'إدارة الجدول',
      'adminCreateOffer': 'إنشاء عرض',
      'adminViewReviews': 'عرض التقييمات',
      'adminManageSubAdmins': 'إدارة المشرفين',
      'adminBookingRequests': 'طلبات الحجز',
      'adminBookingRequestsSubtitle': 'إدارة الطلبات',
      'adminConfirm': 'تأكيد',
      'adminReject': 'رفض',
      'adminPaymentReview': 'مراجعة المدفوعات',
      'adminPaymentReviewSubtitle': 'التحقق من المدفوعات',
      'adminNoPaymentsPending': 'لا يوجد مدفوعات',
      'adminUnderReview': 'قيد المراجعة',
      'paymentMethodTitle': 'طريقة الدفع',
      'paymentMethodDetails': 'تفاصيل التحويل',
      'paymentUploadReceipt': 'رفع إثبات الدفع',
      'paymentReceiptUploaded': 'تم رفع الإيصال',
      'paymentChangeReceipt': 'تغيير الإيصال',
      'paymentCompleteBtn': 'إتمام الدفع',
      'paymentReceiptRequired': 'يجب رفع الإيصال أولاً',
      'paymentNoMethods': 'لا توجد طرق دفع',
      'paymentCardDetails': 'بيانات البطاقة',
      'paymentCardNumber': 'رقم البطاقة',
      'paymentCardExpiry': 'تاريخ الانتهاء',
      'paymentCardCvv': 'CVV',
      'paymentCardHolder': 'اسم صاحب البطاقة',
      'apple': 'تسجيل الدخول عبر Apple قريباً',
      'offersPageTitle': 'العروض',
      'offersTopDeals': 'أفضل العروض',
      'offersEmpty': 'لا توجد عروض حالياً.',
      'notificationsPageTitle': 'الإشعارات',
      'notificationsPageHeader': 'تحديثات لك',
      'notifGroupToday': 'اليوم',
      'notifGroupEarlier': 'سابقاً',
      'save': 'حفظ',
      'weeklyPlanTitle': 'الخطة الأسبوعية',
      'weeklyPlanSaveMore': 'وفر أكثر مع الخطة الأسبوعية',
      'weeklyPlanActivate': 'تفعيل الخطة',
      'weeklyPlanActivated': 'تم تفعيل الخطة بنجاح!',
      'bookingStatusPageTitle': 'حالة الحجز',
      'bookingStatusHeader': 'طلب الحجز',
      'bookingStatusRefreshBtn': 'تحديث الحالة',
      'bookingStatusCancelBtn': 'إلغاء الطلب',
      'bookingStatusGoPaymentBtn': 'الذهاب للدفع',
      'notificationsPageSubtitle': 'حالة الحجز والتنبيهات والنصائح',
      'notifItemTitleApproved': 'تمت الموافقة على الحجز',
      'notifItemSubApproved': 'تم تأكيد حجزك',
      'notifItemTitleRejected': 'تم رفض الحجز',
      'notifItemSubRejected': 'لم يتم قبول الطلب، جرّب خيار آخر',
      'notifItemTitleReminder': 'تذكير بالحجز',
      'notifItemSubReminder': 'موعدك قريب',
      'notifItemTitleOffer': 'عرض جديد',
      'notifItemSubOffer': 'وفر أكثر مع العروض',
      'notifSettingsTitle': 'إعدادات الإشعارات',
      'notifSettingsStayInControl': 'تحكم بالإشعارات',
      'notifSettingsChooseUpdates': 'اختر ما تريد استلامه',
      'notifSettingsBookingReminder': 'تذكير الحجز',
      'notifSettingsReminderSub': 'قبل موعد الحجز',
      'notifSettingsOffersPlans': 'العروض والخطط',
      'notifSettingsOfferSuggestion': 'اقتراحات',
      'notifSettingsOfferSub': 'قد توفر لك المال',
      'usagePageTitle': 'استخدامك',
      'usageBasedOn': 'آخر 30 يوم',
      'usagePlanOptimizer': 'تحسين الخطة',
      'usageComparePlans': 'مقارنة الخطط',
      'usageRecommendation': 'توصية',
      'usageApplyPlan': 'تطبيق الخطة',
      'usagePlanApplied': 'تم التطبيق بنجاح',
      'reviewsPageTitle': 'التقييمات',
      'reviewsFilter': 'تصفية',
      'reviewsAll': 'الكل',
      'reviewsMyReviews': 'مراجعاتي',
      'reviewsMostRecent': 'الأحدث',
      'reviewsRecent': 'مراجعات حديثة',
      'reviewsTip': 'يمكنك تعديل مراجعتك من المساحة',
      'reviewsOverall': 'الإجمالي',
      'reviewsBasedOn': 'بناءً على',
      'reviewsBasedOnSuffix': 'مراجعات',
      'weeklyPlanSubtitle': 'أفضل خيار للاستخدام المتكرر',
      'weeklyPlanWhatYouGet': 'المميزات',
      'bookingStatusPullRefresh': 'اسحب للتحديث',
      'bookingStatusApprovedBanner': 'تمت الموافقة، أكمل الدفع',
      'bookingStatusPaidMsg': 'تم الدفع بنجاح',
      'timelineProgress': 'التقدم',
      'timelineRequestSent': 'تم إرسال الطلب',
      'timelineRequestSentSub': 'استلمنا طلبك',
      'timelineUnderReview': 'قيد المراجعة',
      'timelineUnderReviewSub': 'جارٍ التحقق',
      'timelineUnderReviewWaiting': 'بانتظار المراجعة',
      'timelineUnderReviewCompleted': 'تمت',
      'timelineApproved': 'تمت الموافقة',
      'timelineApprovedSub': 'انتقل للدفع',
      'timelinePaymentCompleted': 'تم الدفع',
      'timelineCancelled': 'ملغي',
      'timelineCancelledSub': 'تم الإلغاء',
      'timelineRejected': 'مرفوض',
      'timelineRejectedSub': 'تم رفض الطلب',
      'summaryRequestId': 'رقم الطلب',
      'summaryStart': 'البداية',
      'summaryDuration': 'المدة',
      'summaryPurpose': 'الغرض',
      'summaryOffer': 'العرض',
      'summaryTotal': 'الإجمالي',
      'kpiTodayTitle': 'حجوزات اليوم',
      'kpiTodayDelta': 'اليوم',
      'kpiPendingTitle': 'طلبات معلقة',
      'kpiNeedsReview': 'تحتاج مراجعة',
      'kpiAllClear': 'كل شيء جيد',
      'kpiSpacesTitle': 'المساحات',
      'kpiSpacesDelta': 'الإجمالي',
      'kpiRevenueTitle': 'الإيرادات',
      'kpiRevenueDelta': 'آخر أسبوع',
      'activityRequested': 'طلب حجز',
      'activityApproved': 'تمت الموافقة',
      'activityPayment': 'تم الدفع',
      'activityConfirmed': 'تم التأكيد',
      'activityCancelled': 'تم الإلغاء',
      'activityBooked': 'حجز',
      'timeJustNow': 'الآن',
      'timeMinAgo': 'دقيقة',
      'timeHoursAgo': 'ساعة',
      'timeDaysAgo': 'يوم',
      'mapShowAll': 'عرض الكل',
      'mapNearby': 'قريب',
      'mapNoResults': 'لا نتائج',
      'mapTitle': 'الخريطة',
      'adminTabHome': 'الرئيسية',
      'adminTabBookings': 'الحجوزات',
      'adminTabUsers': 'المستخدمون',
      'adminTabSubAdmins': 'المشرفون الفرعيون',
      'adminTabSettings': 'الإعدادات',
      'adminSelectedSpace': 'المساحة المحددة',
      'adminSelectSpace': 'اختر مساحة',
      'adminMore': 'المزيد',
      'adminNoRecentActivity': 'لا يوجد نشاط',
      'adminManage': 'إدارة',
      'adminHide': 'إخفاء',
      'adminHidden': 'مخفي',
      'adminAvailable': 'متاح',
      'adminAvailability': 'الحالة',
      'adminImage': 'صورة',
      'adminDelete': 'حذف',
      'adminRetry': 'إعادة المحاولة',
      'adminBack': 'رجوع',
      'adminNone': 'لا يوجد',
      'adminSaving': 'جارٍ الحفظ...',
      'subAdminsTitle': 'المشرفون الفرعيون',
      'subAdminsSubtitle': 'إدارة حسابات محدودة الصلاحيات',
      'subAdminsNoItems': 'لا يوجد مشرفون بعد',
      'subAdminCreate': 'إضافة مشرف',
      'subAdminEdit': 'تعديل مشرف',
      'subAdminRemove': 'حذف مشرف',
      'subAdminAssignSpaces': 'تعيين مساحات',
      'subAdminAssignedSpaces': 'المساحات المعينة',
      'subAdminNoSpaces': 'لا توجد مساحات',
      'subAdminNameLabel': 'الاسم',
      'subAdminNameHint': 'الاسم الكامل',
      'subAdminPasswordHint': 'على الأقل 6 أحرف',
      'subAdminFillAll': 'يرجى تعبئة جميع الحقول',
      'adminTabPending': 'قيد الانتظار',
      'adminTabApproved': 'تمت الموافقة',
      'adminTabCanceled': 'ملغية',
      'adminTabPayReview': 'مراجعة الدفع',
      'adminBookingDetails': 'تفاصيل الحجز',
      'adminCustomerInfo': 'معلومات المستخدم',
      'adminBookingInfo': 'معلومات الحجز',
      'adminCancelBooking': 'إلغاء الحجز',
      'adminCancelReason': 'سبب الإلغاء',
      'adminCancelReasonHint': 'اكتب السبب...',
      'adminConfirmCancel': 'تأكيد الإلغاء',
      'adminConfirmBooking': 'تأكيد الحجز',
      'adminField': 'الحقل',
      'adminDetailsCol': 'القيمة',
      'adminKvSpace': 'المساحة',
      'adminKvAddress': 'العنوان',
      'adminKvDate': 'التاريخ',
      'adminKvTime': 'الوقت',
      'adminKvDuration': 'المدة',
      'adminKvPlan': 'الخطة',
      'adminKvPrice': 'السعر',
      'adminKvTotal': 'الإجمالي',
      'adminMySpaces': 'مساحاتي',
      'adminMySpacesSubtitle': 'إدارة المساحات',
      'adminDeleteSpace': 'حذف المساحة',
      'adminDeleteSpaceConfirm': 'هل أنت متأكد من الحذف؟ لا يمكن التراجع.',
      'adminAddSpace': 'إضافة مساحة',
      'adminEditSpace': 'تعديل مساحة',
      'adminUpdateSpaceInfo': 'تحديث البيانات',
      'adminSpaceName': 'اسم المساحة',
      'adminSpaceNameHint': 'اكتب الاسم',
      'adminAddressLabel': 'العنوان',
      'adminAddressHint': 'مثال: شارع الملك',
      'adminTotalSeats': 'عدد المقاعد',
      'adminSeatsHint': 'مثال: 20',
      'adminSeats': 'مقاعد',
      'adminSpaceAdmin': 'مسؤول المساحة',
      'adminAssignSubAdmin': 'تعيين مشرف',
      'adminSelectSubAdmin': 'اختر مشرف (اختياري)',
      'adminFailedLoad': 'فشل التحميل',
      'adminPaymentUser': 'المستخدم',
      'adminPaymentAmount': 'المبلغ',
      'adminPaymentMethod': 'طريقة الدفع',
      'adminPaymentPaidAt': 'وقت الدفع',
      'adminPaymentReceipt': 'إيصال الدفع',
      'adminViewReceipt': 'عرض الإيصال',
      'adminNoReceipt': 'لا يوجد إيصال',
      'adminPaymentMethodsTitle': 'طرق الدفع',
      'adminPaymentMethodsSubtitle': 'اختر الطريقة وأدخل البيانات',
      'adminPaymentAccountDetails': 'تفاصيل الحساب',
      'adminPaymentAccountDetailsHint': 'رقم الحساب أو IBAN',
      'adminSelectPaymentMethod': 'اختر طريقة الدفع',
      'adminAddPaymentMethod': 'إضافة',
      'adminPaymentAccountName': 'اسم صاحب الحساب',
      'adminPaymentAccountNameHint': 'الاسم الكامل',
      'adminPaymentPhone': 'رقم الهاتف',
      'adminPaymentCardNote': 'الدفع بالبطاقة يتم عند الوصول.',
      'adminSettings': 'الإعدادات',
      'adminAnalytics': 'الإحصائيات',
      'adminPerformance': 'الأداء',
      'adminPerformanceSubtitle': 'تقارير الأداء',
      'adminTopSpaces': 'أفضل المساحات',
      'adminTopSpacesSubtitle': 'الأكثر استخداماً',
      'adminAdminActions': 'إجراءات الإدارة',
      'adminViewRequestsSubtitle': 'كل الطلبات',
      'adminManageCalendarSubtitle': 'إدارة المواعيد',
      'adminOffersManagement': 'إدارة العروض',
      'adminOffersManagementSubtitle': 'الخصومات',
      'adminReviewsReports': 'التقييمات',
      'adminReviewsReportsSubtitle': 'إدارة التعليقات',
      'adminAccount': 'الحساب',
      'adminLogout': 'تسجيل الخروج',
      'adminLogoutSubtitle': 'الخروج من الحساب',
      'adminUsersTitle': 'المستخدمون',
      'adminUsersSubtitle': 'إدارة المستخدمين',
      'adminSearchUsers': 'بحث...',
      'adminFilterAll': 'الكل',
      'adminFilterNew': 'جديد',
      'adminFilterFlagged': 'مُبلغ عنه',
      'insBestForYou': 'الأفضل لك',
      'insBestForYouSub': 'اعثر على المساحة المناسبة لهدفك',
      'insExclusiveDeals': 'عروض حصرية',
      'insExclusiveDealsSub': 'أفضل العروض على المساحات',
      'insWeeklyPlan': 'الخطة الأسبوعية',
      'insMeetingChecklist': 'تجهيزات الاجتماع',
      'insMeetingChecklistSub': 'لا تنسَ الأساسيات للاجتماع',
      'enterEmail': 'أدخل بريدك الإلكتروني وسنرسل لك التعليمات',
      'forgotPassword': 'نسيت كلمة المرور',
    },
  };

  static String tr(String code, String key) {
    return translations[code]?[key] ?? key;
  }
}
