import 'dart:ui';
import 'local_storage_service.dart';

class AppLanguage {
  final String code;
  final String label;

  const AppLanguage({required this.code, required this.label});

  Locale get locale => Locale(code);
}

class LanguageService {
  LanguageService(this._storage);

  final LocalStorageService _storage;

  static const supported = <AppLanguage>[
    AppLanguage(code: 'en', label: 'English'),
    AppLanguage(code: 'ar', label: 'العربية'),
  ];

  /// ================================
  /// Load & Save Language
  /// ================================

  Future<AppLanguage> loadLanguage() async {
    final saved = await _storage.getLocaleCode();
    final found = supported.where((e) => e.code == saved).toList();

    if (found.isNotEmpty) return found.first;
    return supported.first;
  }

  Future<void> setLanguage(String code) async {
    await _storage.setLocaleCode(code);
  }

  /// ================================
  /// Translations
  /// ================================

  static final Map<String, Map<String, String>> translations = {
    'en': {
      // ── Auth ──
      'login': 'Login',
      'signUp': 'Sign Up',
      'email': 'Email',
      'password': 'Password',
      'confirmPassword': 'Confirm Password',
      'fullName': 'Full Name',
      'forgetPassword': 'Forget Password?',
      'dontHaveAccount': "Don't have an account? ",
      'youHaveAccount': 'You have an account? ',
      'or': 'or',
      'english': 'English',
      'arabic': 'العربية',
      'pleaseWait': 'Please wait...',
      'pleaseFillAllFields': 'Please fill all fields',
      'passwordsDoNotMatch': 'Passwords do not match',
      'passwordLength': 'Password must be at least 6 characters',
      'accountCreated': 'Account created successfully!',
      'passwordResetTitle': 'Password Reset',
      'passwordResetBody':
          'A reset email has been sent to your address.\nPlease check your inbox and follow the instructions.',
      'ok': 'OK',
      'send': 'Send',
      'backToLogin': 'Back to Login',
      // ── Onboarding common ──
      'skip': 'Skip',
      'next': 'Next',
      'goToHome': 'Go To Home',
      // ── Onboarding Step 1 ──
      'findPerfectWorkspace': 'Find your perfect workspace',
      'bookStudySpaces':
          'Book work and study spaces with clear\nprices, real insights, and flexible plans.',
      'clearInfoBeforeBook': 'Clear info before you book',
      'clearInfoSubtitle': 'Price, rating, internet quality, and noise level.',
      'whyMashtak': 'Why Mashtak',
      'bookWithConfidence': 'Book with confidence',
      'bookWithConfidenceSubtitle': 'Requests are approved before payment.',
      'smartSuggestions': 'Smart suggestions',
      'smartSuggestionsSubtitle': 'AI highlights the best spaces for your goal.',
      // ── Onboarding Step 2 ──
      'whatAreYouBookingFor': 'What are you booking for?',
      'selectAllThatApply':
          "Select all that apply. We'll tailor\nspaces to your needs.",
      'mainPurpose': 'Main purpose',
      'selectMultiple': 'Select multiple',
      'whatMattersMost': 'What matters most?',
      'whatMattersOptional': 'Optional — helps us rank results better.',
      'youllSeeInsightsLike': "You'll see insights like",
      'insightBestStudy': 'Best for study',
      'insightQuietInternet': 'Quiet + strong internet',
      'insightWeeklySaves': 'Weekly saves more',
      'aiWillUseYourChoices': 'AI will use your choices',
      'aiSubtitle': 'Smarter suggestions + review summaries\n(not a chatbot).',
      'aiFootnote': 'You can change these later in Settings.',
      // ── Onboarding Step 2 — Purposes ──
      'purposeStudy': 'Study',
      'purposeDeepFocus': 'Deep Focus',
      'purposeMeetings': 'Meetings',
      'purposeTeamWork': 'Team Work',
      'purposeCallsInterviews': 'Calls / Interviews',
      'purposeCreative': 'Creative',
      // ── Onboarding Step 2 — Matters ──
      'matterQuiet': 'Quiet',
      'matterFastWifi': 'Fast Wi-Fi',
      'matterBudgetFriendly': 'Budget friendly',
      // ── Onboarding Step 3 ──
      'stayUpdated': 'Stay updated',
      'chooseAlerts': 'Choose the alerts you want.\nYou can change them anytime.',
      'bookingAlerts': 'Booking alerts',
      'bookingApproved': 'Booking approved',
      'bookingApprovedSubtitle': 'When a space confirms your request.',
      'bookingRejected': 'Booking rejected',
      'bookingRejectedSubtitle': 'So you can quickly pick another option.',
      'reminderBeforeBooking': 'Reminder before booking',
      'reminderBeforeBookingSubtitle':
          'A quick reminder before your reserved time.',
      'reminderTiming': 'Reminder timing',
      'optionalLabel': '(Optional)',
      'notificationsHelp': 'Notifications help you trust bookings',
      'notificationsSubtitle':
          'Get approvals, rejections, and reminders\nright on time.',
      'notificationsFootnote':
          "Tip: You'll still see booking status inside the Bookings tab.",
      // ── Onboarding — Reminder timings ──
      'timing30min': '30 min',
      'timing1hour': '1 hour',
      'timingSameDay': 'Same day (9 AM)',
      // ── Bottom Navigation ──
      'navHome': 'Home',
      'navBookings': 'Bookings',
      'navProfile': 'Profile',
      'navSettings': 'Settings',
      // ── Home Tab ──
      'homeTitle': 'Home',
      'searchHint': 'Search',
      'aiConcierge': 'AI Concierge',
      'catNearly': 'Nearly',
      'catNewSuggestion': 'New Suggestion',
      'catPrivateOffice': 'Private Office',
      'forYou': 'For You',
      'noSpacesYet': 'No spaces yet',
      'insightsSection': 'Insights',
      'noInsightsYet': 'No insights yet',
      'view': 'View',
      // ── Home Insights ──
      'insBestForYou': 'Best For You',
      'insBestForYouSub': 'Find the space that matches your goal.',
      'insExclusiveDeals': 'Exclusive Deals',
      'insExclusiveDealsSub': 'Exclusive deals on top spaces.',
      'insWeeklyPlan': 'Weekly Plan',
      'insWeeklyPlanSub': 'Unlock your productivity hub.',
      'insMeetingChecklist': 'Meeting-ready checklist',
      'insMeetingChecklistSub': "Don't miss the essentials.",
      // ── Offers Page ──
      'offersPageTitle': 'Offers',
      'offersTopDeals': 'Top Deals',
      'offersEmpty': 'No offers available right now.',
      // ── Bookings Tab ──
      'upcomingBookings': 'Your Upcoming Bookings',
      'pastBookings': 'Past Bookings',
      'cancelledBookings': 'Cancelled Bookings',
      'noBookingsYet': 'No bookings yet',
      'cancel': 'Cancel',
      'rebook': 'Rebook',
      'manageBooking': 'Manage booking',
      'bookingStatusUpcoming': 'Upcoming',
      'bookingStatusCompleted': 'Completed',
      'bookingStatusCancelled': 'Cancelled',
      'bookingIdLabel': 'Booking ID:',
      'pricePerDay': '/day',
      'bookingInfoLabel': 'Booking info',
      'bookingDateLabel': 'Date',
      'bookingTimeLabel': 'Time',
      'bookingNotesLabel': 'Notes',
      'bookingTotalLabel': 'Total',
      'bookingDetailsTitle': 'Booking Details',
      // ── Profile Tab ──
      'profileTitle': 'Profile',
      'saved': 'Saved',
      'reviews': 'Reviews',
      'personalInfo': 'Personal Info',
      'yourUsage': 'Your usage',
      'paymentsReceipts': 'Payments & Receipts',
      'paymentDetails': 'Payment Details',
      'reviewsRatings': 'Reviews & Ratings',
      'savedSpaces': 'Saved Spaces',
      'logOut': 'Log Out',
      // ── Settings Tab ──
      'settingsTitle': 'Settings',
      'preferences': 'Preferences',
      'workspacePreferences': 'Workspace preferences',
      'workspacePreferencesSub': 'Study, work, meetings',
      'location': 'Location',
      'locationSub': 'Nearby & map search',
      'notifications': 'Notifications',
      'notificationsSub': 'Booking & offers',
      'appLanguage': 'Language',
      'appLanguageSub': 'English / Arabic',
      'chooseLanguage': 'Choose language',
      'close': 'Close',
      'support': 'Support',
      'helpSupport': 'Help & support',
      'helpSupportSub': 'FAQs, contact us',
      'aboutMashtak': 'About Mashtak',
      'aboutMashatakSub': 'Version, terms, privacy',
      'retry': 'Retry',
      // ── Notifications Page ──
      'notificationsPageTitle': 'Notifications',
      'notificationsPageHeader': 'Updates for you',
      'notificationsPageSubtitle': 'Booking status, reminders, and smart plan tips.',
      'notifGroupToday': 'TODAY',
      'notifGroupEarlier': 'EARLIER',
      // ── Notification Item Content ──
      'notifItemTitleApproved': 'Booking Approved! 🎉',
      'notifItemSubApproved': 'Your booking has been confirmed.',
      'notifItemTitleRejected': 'Booking Rejected',
      'notifItemSubRejected': 'Your request could not be accepted. Try another space.',
      'notifItemTitleReminder': 'Booking Reminder ⏰',
      'notifItemSubReminder': 'Your session is starting soon. Get ready!',
      'notifItemTitleOffer': 'New Weekly Deal 🔥',
      'notifItemSubOffer': 'Save more with the weekly pass. Limited spots!',
      // ── Notification Settings Page ──
      'notifSettingsTitle': 'Notification Settings',
      'notifSettingsStayInControl': 'Stay in control',
      'notifSettingsChooseUpdates': 'Choose which updates you want to receive.',
      'notifSettingsBookingReminder': 'Booking reminder',
      'notifSettingsReminderSub': 'Reminder before your reserved time.',
      'notifSettingsOffersPlans': 'Offers & plans',
      'notifSettingsOfferSuggestion': 'Offer / plan suggestion',
      'notifSettingsOfferSub': 'Weekly plan could save you money.',
      'save': 'Save',
      // ── Usage Page ──
      'usagePageTitle': 'Your Usage',
      'usageBasedOn': 'Based on your last 30 days',
      'usagePlanOptimizer': 'Plan Optimizer',
      'usageComparePlans': 'Compare plans',
      'usageRecommendation': 'Recommendation',
      'usageApplyPlan': 'Apply Plan',
      'usagePlanApplied': 'Plan applied successfully!',
      // ── Reviews Page ──
      'reviewsPageTitle': 'Reviews & Ratings',
      'reviewsFilter': 'Filter',
      'reviewsAll': 'All',
      'reviewsMyReviews': 'My reviews',
      'reviewsMostRecent': 'Most recent',
      'reviewsRecent': 'Recent reviews',
      'reviewsTip': 'Tip: You can edit your reviews from Space',
      'reviewsOverall': 'Overall',
      'reviewsBasedOn': 'Based on',
      'reviewsBasedOnSuffix': 'reviews',
      // ── Weekly Plan Page ──
      'weeklyPlanTitle': 'Weekly Plan',
      'weeklyPlanSaveMore': 'Save more with weekly access',
      'weeklyPlanSubtitle': 'Best option for frequent visits and focused work',
      'weeklyPlanWhatYouGet': 'What you get',
      'weeklyPlanActivate': 'Activate plan',
      'weeklyPlanActivated': 'Plan activated successfully!',
      // ── Booking Status Page ──
      'bookingStatusPageTitle': 'Booking status',
      'bookingStatusHeader': 'Booking request',
      'bookingStatusPullRefresh': 'Pull to refresh for latest status',
      'bookingStatusApprovedBanner': 'Booking is approved. Please proceed to payment.',
      'bookingStatusRefreshBtn': 'Refresh status',
      'bookingStatusCancelBtn': 'Cancel request',
      'bookingStatusGoPaymentBtn': 'Go to payment',
      'bookingStatusPaidMsg': 'Paid successfully. You can view booking details from your bookings list.',
      // ── Booking Timeline ──
      'timelineProgress': 'Progress',
      'timelineRequestSent': 'Request sent',
      'timelineRequestSentSub': 'We received your request',
      'timelineUnderReview': 'Under review',
      'timelineUnderReviewSub': 'Checking availability',
      'timelineUnderReviewWaiting': 'Waiting to start review',
      'timelineUnderReviewCompleted': 'Completed',
      'timelineApproved': 'Approved',
      'timelineApprovedSub': 'Proceed to payment',
      'timelinePaymentCompleted': 'Payment completed',
      'timelineCancelled': 'Cancelled',
      'timelineCancelledSub': 'Request cancelled by user',
      'timelineRejected': 'Rejected',
      'timelineRejectedSub': 'Request rejected',
      // ── Booking Summary Card ──
      'summaryRequestId': 'Request ID',
      'summaryStart': 'Start',
      'summaryDuration': 'Duration',
      'summaryPurpose': 'Purpose',
      'summaryOffer': 'Offer',
      'summaryTotal': 'Total',
      // ── Status Badges ──
      'statusPending': 'Pending',
      'statusUnderReview': 'Under review',
      'statusApproved': 'Approved',
      'statusRejected': 'Rejected',
      'statusCancelled': 'Cancelled',
      'statusPaid': 'Paid',
      'statusLoading': 'Loading',
      // ── Admin ──
      'adminTabHome': 'Home',
      'adminTabBookings': 'Bookings',
      'adminTabUsers': 'Users',
      'adminTabSubAdmins': 'Sub Admins',
      'adminTabSettings': 'Settings',
      'adminDashboardTitle': 'Admin Dashboard',
      'adminDashboardSubtitle': 'Manage your coworking spaces',
      'adminSelectedSpace': 'Selected Space',
      'adminSelectSpace': 'Select Space',
      'adminRecentActivity': 'Recent Activity',
      'adminMore': 'More',
      'adminNoRecentActivity': 'No recent activity',
      'adminQuickActions': 'Quick Actions',
      'adminViewRequests': 'View Requests',
      'adminManageCalendar': 'Manage Calendar',
      'adminCreateOffer': 'Create Offer',
      'adminViewReviews': 'View Reviews',
      'adminManageSubAdmins': 'Manage Sub Admins',
      'adminManage': 'Manage',
      'adminHide': 'Hide',
      'adminHidden': 'Hidden',
      'adminAvailable': 'Available',
      'adminAvailability': 'Availability',
      'adminImage': 'Image',
      'adminDelete': 'Delete',
      'adminRetry': 'Retry',
      'adminBack': 'Back',
      'adminNone': 'None',
      'adminConfirm': 'Confirm',
      'adminReject': 'Reject',
      'adminSaving': 'Saving...',
      // Sub Admins
      'subAdminsTitle': 'Sub Admins',
      'subAdminsSubtitle': 'Manage restricted admin accounts',
      'subAdminsNoItems': 'No sub admins yet. Tap + to create one.',
      'subAdminCreate': 'Create Sub Admin',
      'subAdminEdit': 'Edit Sub Admin',
      'subAdminRemove': 'Remove Sub Admin',
      'subAdminAssignSpaces': 'Assign Spaces',
      'subAdminAssignedSpaces': 'Assigned Spaces',
      'subAdminNoSpaces': 'No spaces assigned',
      'subAdminNameLabel': 'Name',
      'subAdminNameHint': 'Full name',
      'subAdminPasswordHint': 'Min 6 characters',
      'subAdminFillAll': 'Please fill all fields',
      // Booking Requests
      'adminBookingRequests': 'Booking Requests',
      'adminBookingRequestsSubtitle': 'Manage booking requests',
      'adminTabPending': 'Pending',
      'adminTabApproved': 'Approved',
      'adminTabCanceled': 'Canceled',
      'adminTabPayReview': 'Pay Review',
      // Booking Details
      'adminBookingDetails': 'Booking Details',
      'adminCustomerInfo': 'Customer Information',
      'adminBookingInfo': 'Booking Information',
      'adminCancelBooking': 'Cancel Booking',
      'adminCancelReason': 'Please provide a reason for cancellation',
      'adminCancelReasonHint': 'Enter cancellation reason...',
      'adminConfirmCancel': 'Confirm Cancel',
      'adminConfirmBooking': 'Confirm Booking',
      'adminField': 'Field',
      'adminDetailsCol': 'Details',
      'adminKvSpace': 'Space',
      'adminKvAddress': 'Address',
      'adminKvDate': 'Date',
      'adminKvTime': 'Time',
      'adminKvDuration': 'Duration',
      'adminKvPlan': 'Plan',
      'adminKvPrice': 'Price',
      'adminKvTotal': 'Total',
      // My Spaces
      'adminMySpaces': 'My Spaces',
      'adminMySpacesSubtitle': 'Manage your listed spaces',
      'adminDeleteSpace': 'Delete Space',
      'adminDeleteSpaceConfirm': 'Are you sure you want to delete this space? This action cannot be undone.',
      // Add/Edit Space
      'adminAddSpace': 'Add Space',
      'adminEditSpace': 'Edit Space',
      'adminUpdateSpaceInfo': 'Update your space info',
      'adminSpaceName': 'Name',
      'adminSpaceNameHint': 'Space name',
      'adminAddressLabel': 'Address (text)',
      'adminAddressHint': 'e.g. 12 King St, Downtown',
      'adminTotalSeats': 'Total Seats',
      'adminSeatsHint': 'e.g. 20',
      'adminSeats': 'seats',
      'adminSpaceAdmin': 'Space Admin',
      'adminAssignSubAdmin': 'Assign Sub Admin',
      'adminSelectSubAdmin': 'Select sub admin (optional)',
      'adminFailedLoad': 'Failed to load space',
      // Payment Review
      'adminPaymentReview': 'Payment Review',
      'adminPaymentReviewSubtitle': 'Verify incoming payments',
      'adminNoPaymentsPending': 'No payments pending review',
      'adminUnderReview': 'Under Review',
      'adminPaymentUser': 'User',
      'adminPaymentAmount': 'Amount',
      'adminPaymentMethod': 'Method',
      'adminPaymentPaidAt': 'Paid at',
      // Settings
      'adminSettings': 'Settings',
      'adminAnalytics': 'Analytics',
      'adminPerformance': 'Performance',
      'adminPerformanceSubtitle': 'KPIs & weekly bookings',
      'adminTopSpaces': 'Top Spaces',
      'adminTopSpacesSubtitle': 'Top performing + export',
      'adminAdminActions': 'Admin actions',
      'adminViewRequestsSubtitle': 'Pending/approved/canceled',
      'adminManageCalendarSubtitle': 'Closures & special hours',
      'adminOffersManagement': 'Offers Management',
      'adminOffersManagementSubtitle': 'Discounts & packages',
      'adminReviewsReports': 'Reviews & Reports',
      'adminReviewsReportsSubtitle': 'Moderation & replies',
      'adminAccount': 'Account',
      'adminLogout': 'Logout',
      'adminLogoutSubtitle': 'Sign out of admin account',
      // Users
      'adminUsersTitle': 'Users',
      'adminUsersSubtitle': 'Search and manage users',
      'adminSearchUsers': 'Search users...',
      'adminFilterAll': 'All',
      'adminFilterNew': 'New',
      'adminFilterFlagged': 'Flagged',
    },
    'ar': {
      // ── Auth ──
      'login': 'تسجيل الدخول',
      'signUp': 'إنشاء حساب',
      'email': 'البريد الإلكتروني',
      'password': 'كلمة المرور',
      'confirmPassword': 'تأكيد كلمة المرور',
      'fullName': 'الاسم الكامل',
      'forgetPassword': 'نسيت كلمة المرور؟',
      'dontHaveAccount': 'ليس لديك حساب؟ ',
      'youHaveAccount': 'لديك حساب؟ ',
      'or': 'أو',
      'english': 'English',
      'arabic': 'العربية',
      'pleaseWait': 'الرجاء الانتظار...',
      'pleaseFillAllFields': 'الرجاء ملء جميع الحقول',
      'passwordsDoNotMatch': 'كلمات المرور غير متطابقة',
      'passwordLength': 'يجب أن تكون كلمة المرور 6 أحرف على الأقل',
      'accountCreated': 'تم إنشاء الحساب بنجاح!',
      'passwordResetTitle': 'إعادة تعيين كلمة المرور',
      'passwordResetBody':
          'تم ارسال بريد الكتروني الى عنوان بريدك.\nقم بتفقد بريدك ومتابعة الاوامر من هناك.',
      'ok': 'حسنًا',
      'send': 'إرسال',
      'backToLogin': 'العودة لتسجيل الدخول',
      // ── Onboarding common ──
      'skip': 'تخطي',
      'next': 'التالي',
      'goToHome': 'انتقل للرئيسية',
      // ── Onboarding Step 1 ──
      'findPerfectWorkspace': 'ابحث عن مساحة عملك المثالية',
      'bookStudySpaces':
          'احجز مساحات عمل ودراسة بأسعار واضحة، رؤى حقيقية، وخطط مرنة.',
      'clearInfoBeforeBook': 'معلومات واضحة قبل الحجز',
      'clearInfoSubtitle': 'السعر، التقييم، جودة الإنترنت، ومستوى الضوضاء.',
      'whyMashtak': 'لماذا مساحتك',
      'bookWithConfidence': 'احجز بثقة',
      'bookWithConfidenceSubtitle': 'يتم الموافقة على الطلبات قبل الدفع.',
      'smartSuggestions': 'اقتراحات ذكية',
      'smartSuggestionsSubtitle':
          'الذكاء الاصطناعي يبرز أفضل المساحات لهدفك.',
      // ── Onboarding Step 2 ──
      'whatAreYouBookingFor': 'ماذا ستحجز؟',
      'selectAllThatApply': 'اختر كل ما ينطبق. سنخصص المساحات وفق احتياجاتك.',
      'mainPurpose': 'الغرض الرئيسي',
      'selectMultiple': 'اختر متعدد',
      'whatMattersMost': 'ما الأهم لك؟',
      'whatMattersOptional': 'اختياري — يساعدنا في ترتيب النتائج.',
      'youllSeeInsightsLike': 'ستشاهد رؤى مثل',
      'insightBestStudy': 'الأفضل للدراسة',
      'insightQuietInternet': 'هادئ + إنترنت قوي',
      'insightWeeklySaves': 'الأسبوعي يوفر أكثر',
      'aiWillUseYourChoices': 'الذكاء الاصطناعي سيستخدم اختياراتك',
      'aiSubtitle': 'اقتراحات أذكى + ملخصات مراجعات\n(ليس روبوتًا للدردشة).',
      'aiFootnote': 'يمكنك تغيير هذه الإعدادات لاحقًا في الإعدادات.',
      // ── Onboarding Step 2 — Purposes ──
      'purposeStudy': 'دراسة',
      'purposeDeepFocus': 'تركيز عميق',
      'purposeMeetings': 'اجتماعات',
      'purposeTeamWork': 'عمل جماعي',
      'purposeCallsInterviews': 'مكالمات / مقابلات',
      'purposeCreative': 'إبداعي',
      // ── Onboarding Step 2 — Matters ──
      'matterQuiet': 'هادئ',
      'matterFastWifi': 'واي فاي سريع',
      'matterBudgetFriendly': 'موفر للميزانية',
      // ── Onboarding Step 3 ──
      'stayUpdated': 'ابقَ على اطلاع',
      'chooseAlerts': 'اختر التنبيهات التي تريدها.\nيمكنك تغييرها في أي وقت.',
      'bookingAlerts': 'تنبيهات الحجز',
      'bookingApproved': 'تم الموافقة على الحجز',
      'bookingApprovedSubtitle': 'عندما تؤكد مساحة طلبك.',
      'bookingRejected': 'تم رفض الحجز',
      'bookingRejectedSubtitle': 'حتى تتمكن من اختيار خيار آخر بسرعة.',
      'reminderBeforeBooking': 'تذكير قبل الحجز',
      'reminderBeforeBookingSubtitle': 'تذكير سريع قبل وقت حجزك.',
      'reminderTiming': 'وقت التذكير',
      'optionalLabel': '(اختياري)',
      'notificationsHelp': 'التنبيهات تساعدك على الثقة بالحجوزات',
      'notificationsSubtitle':
          'احصل على موافقات، رفض، وتذكيرات في الوقت المناسب.',
      'notificationsFootnote':
          'نصيحة: ستشاهد حالة الحجز داخل تبويب الحجوزات.',
      // ── Onboarding — Reminder timings ──
      'timing30min': '30 دقيقة',
      'timing1hour': 'ساعة واحدة',
      'timingSameDay': 'نفس اليوم (9 ص)',
      // ── Bottom Navigation ──
      'navHome': 'الرئيسية',
      'navBookings': 'الحجوزات',
      'navProfile': 'الملف الشخصي',
      'navSettings': 'الإعدادات',
      // ── Home Tab ──
      'homeTitle': 'الرئيسية',
      'searchHint': 'ابحث',
      'aiConcierge': 'مساعد ذكي',
      'catNearly': 'القريبة',
      'catNewSuggestion': 'اقتراح جديد',
      'catPrivateOffice': 'مكتب خاص',
      'forYou': 'مختارة لك',
      'noSpacesYet': 'لا توجد مساحات بعد',
      'insightsSection': 'رؤى',
      'noInsightsYet': 'لا توجد رؤى بعد',
      'view': 'عرض',
      // ── Home Insights ──
      'insBestForYou': 'الأنسب لك',
      'insBestForYouSub': 'ابحث عن المساحة التي تناسب هدفك.',
      'insExclusiveDeals': 'عروض حصرية',
      'insExclusiveDealsSub': 'عروض حصرية على أفضل المساحات.',
      'insWeeklyPlan': 'الخطة الأسبوعية',
      'insWeeklyPlanSub': 'اكتشف مركز إنتاجيتك.',
      'insMeetingChecklist': 'قائمة تحضير الاجتماع',
      'insMeetingChecklistSub': 'لا تفوتك الأساسيات.',
      // ── Offers Page ──
      'offersPageTitle': 'العروض',
      'offersTopDeals': 'أفضل الصفقات',
      'offersEmpty': 'لا توجد عروض متاحة الآن.',
      // ── Bookings Tab ──
      'upcomingBookings': 'حجوزاتك القادمة',
      'pastBookings': 'الحجوزات السابقة',
      'cancelledBookings': 'الحجوزات الملغاة',
      'noBookingsYet': 'لا توجد حجوزات بعد',
      'cancel': 'إلغاء',
      'rebook': 'إعادة الحجز',
      'manageBooking': 'إدارة الحجز',
      'bookingStatusUpcoming': 'قادم',
      'bookingStatusCompleted': 'مكتمل',
      'bookingStatusCancelled': 'ملغي',
      'bookingIdLabel': 'رقم الحجز:',
      'pricePerDay': '/يوم',
      'bookingInfoLabel': 'معلومات الحجز',
      'bookingDateLabel': 'التاريخ',
      'bookingTimeLabel': 'الوقت',
      'bookingNotesLabel': 'ملاحظات',
      'bookingTotalLabel': 'الإجمالي',
      'bookingDetailsTitle': 'تفاصيل الحجز',
      // ── Profile Tab ──
      'profileTitle': 'الملف الشخصي',
      'saved': 'المحفوظات',
      'reviews': 'التقييمات',
      'personalInfo': 'المعلومات الشخصية',
      'yourUsage': 'استخدامك',
      'paymentsReceipts': 'المدفوعات والإيصالات',
      'paymentDetails': 'تفاصيل الدفع',
      'reviewsRatings': 'التقييمات والمراجعات',
      'savedSpaces': 'المساحات المحفوظة',
      'logOut': 'تسجيل الخروج',
      // ── Settings Tab ──
      'settingsTitle': 'الإعدادات',
      'preferences': 'التفضيلات',
      'workspacePreferences': 'تفضيلات المساحة',
      'workspacePreferencesSub': 'دراسة، عمل، اجتماعات',
      'location': 'الموقع',
      'locationSub': 'البحث القريب وخريطة',
      'notifications': 'الإشعارات',
      'notificationsSub': 'الحجوزات والعروض',
      'appLanguage': 'اللغة',
      'appLanguageSub': 'العربية / الإنجليزية',
      'chooseLanguage': 'اختر اللغة',
      'close': 'إغلاق',
      'support': 'الدعم',
      'helpSupport': 'المساعدة والدعم',
      'helpSupportSub': 'الأسئلة الشائعة، اتصل بنا',
      'aboutMashtak': 'عن مساحتك',
      'aboutMashatakSub': 'الإصدار، الشروط، الخصوصية',
      'retry': 'إعادة المحاولة',
      // ── Notifications Page ──
      'notificationsPageTitle': 'الإشعارات',
      'notificationsPageHeader': 'تحديثات لك',
      'notificationsPageSubtitle': 'حالة الحجز، تذكيرات، ونصائح الخطة الذكية.',
      'notifGroupToday': 'اليوم',
      'notifGroupEarlier': 'السابق',
      // ── Notification Item Content ──
      'notifItemTitleApproved': 'تمت الموافقة على حجزك! 🎉',
      'notifItemSubApproved': 'تم تأكيد حجزك بنجاح.',
      'notifItemTitleRejected': 'تم رفض الحجز',
      'notifItemSubRejected': 'للأسف لم يتم قبول طلبك. جرب مكاناً آخر.',
      'notifItemTitleReminder': 'تذكير بالحجز ⏰',
      'notifItemSubReminder': 'جلستك ستبدأ قريباً. استعد!',
      'notifItemTitleOffer': 'عرض أسبوعي جديد 🔥',
      'notifItemSubOffer': 'وفّر أكثر مع الباقة الأسبوعية. أماكن محدودة!',
      // ── Notification Settings Page ──
      'notifSettingsTitle': 'إعدادات الإشعارات',
      'notifSettingsStayInControl': 'ابقَ في التحكم',
      'notifSettingsChooseUpdates': 'اختر التحديثات التي تريد استلامها.',
      'notifSettingsBookingReminder': 'تذكير الحجز',
      'notifSettingsReminderSub': 'تذكير قبل وقت حجزك.',
      'notifSettingsOffersPlans': 'العروض والخطط',
      'notifSettingsOfferSuggestion': 'اقتراح عرض / خطة',
      'notifSettingsOfferSub': 'الخطة الأسبوعية قد توفر لك المال.',
      'save': 'حفظ',
      // ── Usage Page ──
      'usagePageTitle': 'استخدامك',
      'usageBasedOn': 'بناءً على آخر 30 يومًا',
      'usagePlanOptimizer': 'محسّن الخطة',
      'usageComparePlans': 'قارن الخطط',
      'usageRecommendation': 'التوصية',
      'usageApplyPlan': 'تطبيق الخطة',
      'usagePlanApplied': 'تم تطبيق الخطة بنجاح!',
      // ── Reviews Page ──
      'reviewsPageTitle': 'التقييمات والمراجعات',
      'reviewsFilter': 'تصفية',
      'reviewsAll': 'الكل',
      'reviewsMyReviews': 'مراجعاتي',
      'reviewsMostRecent': 'الأحدث',
      'reviewsRecent': 'المراجعات الأخيرة',
      'reviewsTip': 'نصيحة: يمكنك تعديل مراجعاتك من صفحة المساحة',
      'reviewsOverall': 'الإجمالي',
      'reviewsBasedOn': 'بناءً على',
      'reviewsBasedOnSuffix': 'تقييم',
      // ── Weekly Plan Page ──
      'weeklyPlanTitle': 'الخطة الأسبوعية',
      'weeklyPlanSaveMore': 'وفّر أكثر مع الوصول الأسبوعي',
      'weeklyPlanSubtitle': 'الخيار الأفضل للزيارات المتكررة والعمل المركّز',
      'weeklyPlanWhatYouGet': 'ما الذي ستحصل عليه',
      'weeklyPlanActivate': 'تفعيل الخطة',
      'weeklyPlanActivated': 'تم تفعيل الخطة بنجاح!',
      // ── Booking Status Page ──
      'bookingStatusPageTitle': 'حالة الحجز',
      'bookingStatusHeader': 'طلب الحجز',
      'bookingStatusPullRefresh': 'اسحب للأسفل لتحديث الحالة',
      'bookingStatusApprovedBanner': 'تمت الموافقة على الحجز. تفضل بإتمام الدفع.',
      'bookingStatusRefreshBtn': 'تحديث الحالة',
      'bookingStatusCancelBtn': 'إلغاء الطلب',
      'bookingStatusGoPaymentBtn': 'الانتقال للدفع',
      'bookingStatusPaidMsg': 'تم الدفع بنجاح. يمكنك مراجعة تفاصيل الحجز من قائمة حجوزاتك.',
      // ── Booking Timeline ──
      'timelineProgress': 'التقدم',
      'timelineRequestSent': 'تم إرسال الطلب',
      'timelineRequestSentSub': 'استلمنا طلبك',
      'timelineUnderReview': 'قيد المراجعة',
      'timelineUnderReviewSub': 'جاري التحقق من التوفر',
      'timelineUnderReviewWaiting': 'بانتظار بدء المراجعة',
      'timelineUnderReviewCompleted': 'مكتمل',
      'timelineApproved': 'تمت الموافقة',
      'timelineApprovedSub': 'تفضل بإتمام الدفع',
      'timelinePaymentCompleted': 'تم الدفع',
      'timelineCancelled': 'ملغي',
      'timelineCancelledSub': 'الطلب ألغاه المستخدم',
      'timelineRejected': 'مرفوض',
      'timelineRejectedSub': 'تم رفض الطلب',
      // ── Booking Summary Card ──
      'summaryRequestId': 'رقم الطلب',
      'summaryStart': 'تاريخ البداية',
      'summaryDuration': 'المدة',
      'summaryPurpose': 'الغرض',
      'summaryOffer': 'العرض',
      'summaryTotal': 'الإجمالي',
      // ── Status Badges ──
      'statusPending': 'قيد الانتظار',
      'statusUnderReview': 'قيد المراجعة',
      'statusApproved': 'تمت الموافقة',
      'statusRejected': 'مرفوض',
      'statusCancelled': 'ملغي',
      'statusPaid': 'مدفوع',
      'statusLoading': 'جاري التحميل',
      // ── Admin ──
      'adminTabHome': 'الرئيسية',
      'adminTabBookings': 'الحجوزات',
      'adminTabUsers': 'المستخدمون',
      'adminTabSubAdmins': 'المشرفون الفرعيون',
      'adminTabSettings': 'الإعدادات',
      'adminDashboardTitle': 'لوحة التحكم',
      'adminDashboardSubtitle': 'إدارة مساحات العمل المشتركة',
      'adminSelectedSpace': 'المساحة المحددة',
      'adminSelectSpace': 'اختر مساحة',
      'adminRecentActivity': 'النشاط الأخير',
      'adminMore': 'المزيد',
      'adminNoRecentActivity': 'لا يوجد نشاط حديث',
      'adminQuickActions': 'إجراءات سريعة',
      'adminViewRequests': 'عرض الطلبات',
      'adminManageCalendar': 'إدارة التقويم',
      'adminCreateOffer': 'إنشاء عرض',
      'adminViewReviews': 'عرض التقييمات',
      'adminManageSubAdmins': 'إدارة المشرفين الفرعيين',
      'adminManage': 'إدارة',
      'adminHide': 'إخفاء',
      'adminHidden': 'مخفي',
      'adminAvailable': 'متاح',
      'adminAvailability': 'التوفر',
      'adminImage': 'صورة',
      'adminDelete': 'حذف',
      'adminRetry': 'إعادة المحاولة',
      'adminBack': 'رجوع',
      'adminNone': 'لا أحد',
      'adminConfirm': 'تأكيد',
      'adminReject': 'رفض',
      'adminSaving': 'جاري الحفظ...',
      // Sub Admins
      'subAdminsTitle': 'المشرفون الفرعيون',
      'subAdminsSubtitle': 'إدارة حسابات المشرفين المقيدة',
      'subAdminsNoItems': 'لا يوجد مشرفون فرعيون. اضغط + لإنشاء واحد.',
      'subAdminCreate': 'إنشاء مشرف فرعي',
      'subAdminEdit': 'تعديل المشرف الفرعي',
      'subAdminRemove': 'إزالة المشرف الفرعي',
      'subAdminAssignSpaces': 'تعيين المساحات',
      'subAdminAssignedSpaces': 'المساحات المعينة',
      'subAdminNoSpaces': 'لا توجد مساحات معينة',
      'subAdminNameLabel': 'الاسم',
      'subAdminNameHint': 'الاسم الكامل',
      'subAdminPasswordHint': 'لا يقل عن 6 أحرف',
      'subAdminFillAll': 'يرجى ملء جميع الحقول',
      // Booking Requests
      'adminBookingRequests': 'طلبات الحجز',
      'adminBookingRequestsSubtitle': 'إدارة طلبات الحجز',
      'adminTabPending': 'قيد الانتظار',
      'adminTabApproved': 'موافق عليه',
      'adminTabCanceled': 'ملغي',
      'adminTabPayReview': 'مراجعة الدفع',
      // Booking Details
      'adminBookingDetails': 'تفاصيل الحجز',
      'adminCustomerInfo': 'معلومات العميل',
      'adminBookingInfo': 'معلومات الحجز',
      'adminCancelBooking': 'إلغاء الحجز',
      'adminCancelReason': 'يرجى تقديم سبب الإلغاء',
      'adminCancelReasonHint': 'أدخل سبب الإلغاء...',
      'adminConfirmCancel': 'تأكيد الإلغاء',
      'adminConfirmBooking': 'تأكيد الحجز',
      'adminField': 'الحقل',
      'adminDetailsCol': 'التفاصيل',
      'adminKvSpace': 'المساحة',
      'adminKvAddress': 'العنوان',
      'adminKvDate': 'التاريخ',
      'adminKvTime': 'الوقت',
      'adminKvDuration': 'المدة',
      'adminKvPlan': 'الباقة',
      'adminKvPrice': 'السعر',
      'adminKvTotal': 'الإجمالي',
      // My Spaces
      'adminMySpaces': 'مساحاتي',
      'adminMySpacesSubtitle': 'إدارة مساحاتك المدرجة',
      'adminDeleteSpace': 'حذف المساحة',
      'adminDeleteSpaceConfirm': 'هل أنت متأكد أنك تريد حذف هذه المساحة؟ لا يمكن التراجع عن هذا الإجراء.',
      // Add/Edit Space
      'adminAddSpace': 'إضافة مساحة',
      'adminEditSpace': 'تعديل المساحة',
      'adminUpdateSpaceInfo': 'تحديث معلومات المساحة',
      'adminSpaceName': 'الاسم',
      'adminSpaceNameHint': 'اسم المساحة',
      'adminAddressLabel': 'العنوان (نص)',
      'adminAddressHint': 'مثال: شارع الملك 12',
      'adminTotalSeats': 'إجمالي المقاعد',
      'adminSeatsHint': 'مثال: 20',
      'adminSeats': 'مقاعد',
      'adminSpaceAdmin': 'مشرف المساحة',
      'adminAssignSubAdmin': 'تعيين مشرف فرعي',
      'adminSelectSubAdmin': 'اختر مشرفاً فرعياً (اختياري)',
      'adminFailedLoad': 'فشل تحميل المساحة',
      // Payment Review
      'adminPaymentReview': 'مراجعة الدفع',
      'adminPaymentReviewSubtitle': 'التحقق من المدفوعات الواردة',
      'adminNoPaymentsPending': 'لا توجد مدفوعات بانتظار المراجعة',
      'adminUnderReview': 'قيد المراجعة',
      'adminPaymentUser': 'المستخدم',
      'adminPaymentAmount': 'المبلغ',
      'adminPaymentMethod': 'الطريقة',
      'adminPaymentPaidAt': 'تاريخ الدفع',
      // Settings
      'adminSettings': 'الإعدادات',
      'adminAnalytics': 'التحليلات',
      'adminPerformance': 'الأداء',
      'adminPerformanceSubtitle': 'مؤشرات الأداء والحجوزات الأسبوعية',
      'adminTopSpaces': 'أفضل المساحات',
      'adminTopSpacesSubtitle': 'الأفضل أداءً + تصدير',
      'adminAdminActions': 'إجراءات الأدمن',
      'adminViewRequestsSubtitle': 'قيد الانتظار / موافق / ملغي',
      'adminManageCalendarSubtitle': 'الإغلاقات وساعات خاصة',
      'adminOffersManagement': 'إدارة العروض',
      'adminOffersManagementSubtitle': 'الخصومات والباقات',
      'adminReviewsReports': 'التقييمات والتقارير',
      'adminReviewsReportsSubtitle': 'الإشراف والردود',
      'adminAccount': 'الحساب',
      'adminLogout': 'تسجيل الخروج',
      'adminLogoutSubtitle': 'تسجيل الخروج من حساب الأدمن',
      // Users
      'adminUsersTitle': 'المستخدمون',
      'adminUsersSubtitle': 'بحث وإدارة المستخدمين',
      'adminSearchUsers': 'بحث عن مستخدمين...',
      'adminFilterAll': 'الكل',
      'adminFilterNew': 'جديد',
      'adminFilterFlagged': 'مبلغ عنه',
    },
  };

  /// Static translator
  static String tr(String code, String key) {
    return translations[code]?[key] ?? key;
  }
}
