import 'dart:ui';
import 'local_storage_service.dart';

class AppLanguage {
  final String code;
  final String label;

  const AppLanguage({required this.code, required this.label});

  Locale get locale => Locale(code);
}

class LanguageService {
  LanguageService(this._storage);

  final LocalStorageService _storage;

  static const supported = <AppLanguage>[
    AppLanguage(code: 'en', label: 'English'),
    AppLanguage(code: 'ar', label: 'العربية'),
  ];

  /// ================================
  /// Load & Save Language
  /// ================================

  Future<AppLanguage> loadLanguage() async {
    final saved = await _storage.getLocaleCode();
    final found = supported.where((e) => e.code == saved).toList();

    if (found.isNotEmpty) return found.first;
    return supported.first;
  }

  Future<void> setLanguage(String code) async {
    await _storage.setLocaleCode(code);
  }

  /// ================================
  /// Translations
  /// ================================

  static final Map<String, Map<String, String>> translations = {
    'en': {
      // ── Auth ──
      'login': 'Login',
      'signUp': 'Sign Up',
      'email': 'Email',
      'password': 'Password',
      'confirmPassword': 'Confirm Password',
      'fullName': 'Full Name',
      'forgetPassword': 'Forget Password?',
      'dontHaveAccount': "Don't have an account? ",
      'youHaveAccount': 'You have an account? ',
      'or': 'or',
      'english': 'English',
      'arabic': 'Arabic',
      'msahtak':'Msahtak',
      'pleaseWait': 'Please wait...',
      'pleaseFillAllFields': 'Please fill all fields',
      'passwordsDoNotMatch': 'Passwords do not match',
      'passwordLength': 'Password must be at least 6 characters',
      'accountCreated': 'Account created successfully!',
      'passwordResetTitle': 'Password Reset',
      'passwordResetBody':
          'A reset email has been sent to your address.\nPlease check your inbox and follow the instructions.',
      'ok': 'OK',
      'send': 'Send',
      'backToLogin': 'Back to Login',
      // ── Onboarding common ──
      'skip': 'Skip',
      'next': 'Next',
      'goToHome': 'Go To Home',
      // ── Onboarding Step 1 ──
      'findPerfectWorkspace': 'Find your perfect workspace',
      'bookStudySpaces':
          'Book work and study spaces with clear\nprices, real insights, and flexible plans.',
      'clearInfoBeforeBook': 'Clear info before you book',
      'clearInfoSubtitle': 'Price, rating, internet quality, and noise level.',
      'whyMashtak': 'Why Mashtak',
      'bookWithConfidence': 'Book with confidence',
      'bookWithConfidenceSubtitle': 'Requests are approved before payment.',
      'smartSuggestions': 'Smart suggestions',
      'smartSuggestionsSubtitle': 'AI highlights the best spaces for your goal.',
      // ── Onboarding Step 2 ──
      'whatAreYouBookingFor': 'What are you booking for?',
      'selectAllThatApply':
          "Select all that apply. We'll tailor\nspaces to your needs.",
      'mainPurpose': 'Main purpose',
      'selectMultiple': 'Select multiple',
      'whatMattersMost': 'What matters most?',
      'whatMattersOptional': 'Optional — helps us rank results better.',
      'youllSeeInsightsLike': "You'll see insights like",
      'insightBestStudy': 'Best for study',
      'insightQuietInternet': 'Quiet + strong internet',
      'insightWeeklySaves': 'Weekly saves more',
      'aiWillUseYourChoices': 'AI will use your choices',
      'aiSubtitle': 'Smarter suggestions + review summaries\n(not a chatbot).',
      'aiFootnote': 'You can change these later in Settings.',
      // ── Onboarding Step 2 — Purposes ──
      'purposeStudy': 'Study',
      'purposeDeepFocus': 'Deep Focus',
      'purposeMeetings': 'Meetings',
      'purposeTeamWork': 'Team Work',
      'purposeCallsInterviews': 'Calls / Interviews',
      'purposeCreative': 'Creative',
      // ── Onboarding Step 2 — Matters ──
      'matterQuiet': 'Quiet',
      'matterFastWifi': 'Fast Wi-Fi',
      'matterBudgetFriendly': 'Budget friendly',
      // ── Onboarding Step 3 ──
      'stayUpdated': 'Stay updated',
      'chooseAlerts': 'Choose the alerts you want.\nYou can change them anytime.',
      'bookingAlerts': 'Booking alerts',
      'bookingApproved': 'Booking approved',
      'bookingApprovedSubtitle': 'When a space confirms your request.',
      'bookingRejected': 'Booking rejected',
      'bookingRejectedSubtitle': 'So you can quickly pick another option.',
      'reminderBeforeBooking': 'Reminder before booking',
      'reminderBeforeBookingSubtitle':
          'A quick reminder before your reserved time.',
      'reminderTiming': 'Reminder timing',
      'optionalLabel': '(Optional)',
      'notificationsHelp': 'Notifications help you trust bookings',
      'notificationsSubtitle':
          'Get approvals, rejections, and reminders\nright on time.',
      'notificationsFootnote':
          "Tip: You'll still see booking status inside the Bookings tab.",
      // ── Onboarding — Reminder timings ──
      'timing30min': '30 min',
      'timing1hour': '1 hour',
      'timingSameDay': 'Same day (9 AM)',
      // ── Bottom Navigation ──
      'navHome': 'Home',
      'navBookings': 'Bookings',
      'navProfile': 'Profile',
      'navSettings': 'Settings',
      // ── Home Tab ──
      'homeTitle': 'Home',
      'searchHint': 'Search',
      'aiConcierge': 'AI Concierge',
      'catNearly': 'Nearly',
      'catNewSuggestion': 'New Suggestion',
      'catPrivateOffice': 'Private Office',
      'forYou': 'For You',
      'noSpacesYet': 'No spaces yet',
      'insightsSection': 'Insights',
      'noInsightsYet': 'No insights yet',
      'view': 'View',
      // ── Home Insights ──
      'insBestForYou': 'Best For You',
      'insBestForYouSub': 'Find the space that matches your goal.',
      'insExclusiveDeals': 'Exclusive Deals',
      'insExclusiveDealsSub': 'Exclusive deals on top spaces.',
      'insWeeklyPlan': 'Weekly Plan',
      'insWeeklyPlanSub': 'Unlock your productivity hub.',
      'insMeetingChecklist': 'Meeting-ready checklist',
      'insMeetingChecklistSub': "Don't miss the essentials.",
      // ── Offers Page ──
      'offersPageTitle': 'Offers',
      'offersTopDeals': 'Top Deals',
      'offersEmpty': 'No offers available right now.',
      // ── Bookings Tab ──
      'upcomingBookings': 'Your Upcoming Bookings',
      'pastBookings': 'Past Bookings',
      'cancelledBookings': 'Cancelled Bookings',
      'awaitingConfirmationTab': 'Awaiting Confirmation',
      'confirmedBookingsTab': 'Confirmed Bookings',
      'noBookingsYet': 'No bookings yet',
      'bookingLoadErrorPrefix': 'Error:',
      'cancel': 'Cancel',
      'rebook': 'Rebook',
      'manageBooking': 'Manage booking',
      'bookingStatusUpcoming': 'Upcoming',
      'bookingStatusCompleted': 'Completed',
      'bookingStatusCancelled': 'Cancelled',
      'bookingStatusAwaitingConfirmation': 'Awaiting Confirmation',
      'bookingStatusConfirmed': 'Confirmed',
      'bookingIdLabel': 'Booking ID:',
      'pricePerDay': '/day',
      'bookingInfoLabel': 'Booking info',
      'bookingDateLabel': 'Date',
      'bookingTimeLabel': 'Time',
      'bookingNotesLabel': 'Notes',
      'bookingTotalLabel': 'Total',
      'bookingDetailsTitle': 'Booking Details',
      'bookingDetailsErrorPrefix': 'Error:',
      'bookingDetailsActionPlaceholder': 'Action (placeholder)',
      // ── Profile Tab ──
      'profileTitle': 'Profile',
      'saved': 'Saved',
      'reviews': 'Reviews',
      'personalInfo': 'Personal Info',
      'yourUsage': 'Your usage',
      'paymentsReceipts': 'Payments & Receipts',
      'paymentDetails': 'Payment Details',
      'reviewsRatings': 'Reviews & Ratings',
      'savedSpaces': 'Saved Spaces',
      'logOut': 'Log Out',
      // ── Settings Tab ──
      'settingsTitle': 'Settings',
      'preferences': 'Preferences',
      'workspacePreferences': 'Workspace preferences',
      'workspacePreferencesSub': 'Study, work, meetings',
      'location': 'Location',
      'locationSub': 'Nearby & map search',
      'notifications': 'Notifications',
      'notificationsSub': 'Booking & offers',
      'appLanguage': 'Language',
      'appLanguageSub': 'English / Arabic',
      'chooseLanguage': 'Choose language',
      'close': 'Close',
      'support': 'Support',
      'helpSupport': 'Help & support',
      'helpSupportSub': 'FAQs, contact us',
      'aboutMashtak': 'About Mashtak',
      'aboutMashatakSub': 'Version, terms, privacy',
      'retry': 'Retry',
      'noInternetTitle': 'No Internet Connection',
      // ── Notifications Page ──
      'notificationsPageTitle': 'Notifications',
      'notificationsPageHeader': 'Updates for you',
      'notificationsPageSubtitle': 'Booking status, reminders, and smart plan tips.',
      'notifGroupToday': 'TODAY',
      'notifGroupEarlier': 'EARLIER',
      // ── Notification Item Content ──
      'notifItemTitleApproved': 'Booking Approved! 🎉',
      'notifItemSubApproved': 'Your booking has been confirmed.',
      'notifItemTitleRejected': 'Booking Rejected',
      'notifItemSubRejected': 'Your request could not be accepted. Try another space.',
      'notifItemTitleReminder': 'Booking Reminder ⏰',
      'notifItemSubReminder': 'Your session is starting soon. Get ready!',
      'notifItemTitleOffer': 'New Weekly Deal 🔥',
      'notifItemSubOffer': 'Save more with the weekly pass. Limited spots!',
      // ── Notification Settings Page ──
      'notifSettingsTitle': 'Notification Settings',
      'notifSettingsStayInControl': 'Stay in control',
      'notifSettingsChooseUpdates': 'Choose which updates you want to receive.',
      'notifSettingsBookingReminder': 'Booking reminder',
      'notifSettingsReminderSub': 'Reminder before your reserved time.',
      'notifSettingsOffersPlans': 'Offers & plans',
      'notifSettingsOfferSuggestion': 'Offer / plan suggestion',
      'notifSettingsOfferSub': 'Weekly plan could save you money.',
      'save': 'Save',
      // ── Usage Page ──
      'usagePageTitle': 'Your Usage',
      'usageBasedOn': 'Based on your last 30 days',
      'usagePlanOptimizer': 'Plan Optimizer',
      'usageComparePlans': 'Compare plans',
      'usageRecommendation': 'Recommendation',
      'usageApplyPlan': 'Apply Plan',
      'usagePlanApplied': 'Plan applied successfully!',
      // ── Reviews Page ──
      'reviewsPageTitle': 'Reviews & Ratings',
      'reviewsFilter': 'Filter',
      'reviewsAll': 'All',
      'reviewsMyReviews': 'My reviews',
      'reviewsMostRecent': 'Most recent',
      'reviewsRecent': 'Recent reviews',
      'reviewsTip': 'Tip: You can edit your reviews from Space',
      'reviewsOverall': 'Overall',
      'reviewsBasedOn': 'Based on',
      'reviewsBasedOnSuffix': 'reviews',
      // ── Weekly Plan Page ──
      'weeklyPlanTitle': 'Weekly Plan',
      'weeklyPlanSaveMore': 'Save more with weekly access',
      'weeklyPlanSubtitle': 'Best option for frequent visits and focused work',
      'weeklyPlanWhatYouGet': 'What you get',
      'weeklyPlanActivate': 'Activate plan',
      'weeklyPlanActivated': 'Plan activated successfully!',
      // ── Booking Status Page ──
      'bookingStatusPageTitle': 'Booking status',
      'bookingStatusHeader': 'Booking request',
      'bookingStatusPullRefresh': 'Pull to refresh for latest status',
      'bookingStatusApprovedBanner': 'Booking is approved. Please proceed to payment.',
      'bookingStatusRefreshBtn': 'Refresh status',
      'bookingStatusCancelBtn': 'Cancel request',
      'bookingStatusGoPaymentBtn': 'Go to payment',
      'bookingStatusPaidMsg': 'Paid successfully. You can view booking details from your bookings list.',
      // ── Booking Timeline ──
      'timelineProgress': 'Progress',
      'timelineRequestSent': 'Request sent',
      'timelineRequestSentSub': 'We received your request',
      'timelineUnderReview': 'Under review',
      'timelineUnderReviewSub': 'Checking availability',
      'timelineUnderReviewWaiting': 'Waiting to start review',
      'timelineUnderReviewCompleted': 'Completed',
      'timelineApproved': 'Approved',
      'timelineApprovedSub': 'Proceed to payment',
      'timelinePaymentCompleted': 'Payment completed',
      'timelineCancelled': 'Cancelled',
      'timelineCancelledSub': 'Request cancelled by user',
      'timelineRejected': 'Rejected',
      'timelineRejectedSub': 'Request rejected',
      // ── Booking Summary Card ──
      'summaryRequestId': 'Request ID',
      'summaryStart': 'Start',
      'summaryDuration': 'Duration',
      'summaryPurpose': 'Purpose',
      'summaryOffer': 'Offer',
      'summaryTotal': 'Total',
      // ── Status Badges ──
      'statusPending': 'Pending',
      'statusUnderReview': 'Under review',
      'statusApproved': 'Approved',
      'statusRejected': 'Rejected',
      'statusCancelled': 'Cancelled',
      'statusPaid': 'Paid',
      'statusLoading': 'Loading',
      // ── KPI Tiles ──
      'kpiTodayTitle': 'Today Bookings',
      'kpiTodayDelta': 'bookings today',
      'kpiPendingTitle': 'Pending Requests',
      'kpiNeedsReview': 'Needs review',
      'kpiAllClear': 'All clear',
      'kpiSpacesTitle': 'Active Spaces',
      'kpiSpacesDelta': 'total spaces',
      'kpiRevenueTitle': 'Weekly Revenue',
      'kpiRevenueDelta': 'last 7 days',
      // ── Activity ──
      'activityRequested': 'requested booking at',
      'activityApproved': 'booking approved for',
      'activityPayment': 'submitted payment for',
      'activityConfirmed': 'confirmed booking at',
      'activityCancelled': 'booking cancelled at',
      'activityBooked': 'booked',
      // ── Time Ago ──
      'timeJustNow': 'just now',
      'timeMinAgo': 'min ago',
      'timeHoursAgo': 'h ago',
      'timeDaysAgo': 'd ago',
      // ── Map ──
      'mapShowAll': 'Show All',
      'mapNearby': 'Nearby',
      'mapNoResults': 'No results in this area.',
      'mapTitle': 'Explore Spaces on Map',
      // ── Admin ──
      'adminTabHome': 'Home',
      'adminTabBookings': 'Bookings',
      'adminTabUsers': 'Users',
      'adminTabSubAdmins': 'Assistants',
      'adminTabSettings': 'Settings',
      'adminDashboardTitle': 'Admin Dashboard',
      'adminDashboardSubtitle': 'Manage your coworking spaces',
      'adminSelectedSpace': 'Selected Space',
      'adminSelectSpace': 'Select Space',
      'adminRecentActivity': 'Recent Activity',
      'adminMore': 'More',
      'adminNoRecentActivity': 'No recent activity',
      'adminQuickActions': 'Quick Actions',
      'adminViewRequests': 'View Requests',
      'adminManageCalendar': 'Manage Calendar',
      'adminCreateOffer': 'Create Offer',
      'adminViewReviews': 'View Reviews',
      'adminManageSubAdmins': 'Manage Sub Admins',
      'adminManage': 'Manage',
      'adminHide': 'Hide',
      'adminHidden': 'Hidden',
      'adminAvailable': 'Available',
      'adminAvailability': 'Availability',
      'adminImage': 'Image',
      'adminDelete': 'Delete',
      'adminRetry': 'Retry',
      'adminBack': 'Back',
      'adminNone': 'None',
      'adminConfirm': 'Confirm',
      'adminReject': 'Reject',
      'adminSaving': 'Saving...',
      // Sub Admins
      'subAdminsTitle': 'Assistants',
      'subAdminsSubtitle': 'Manage restricted admin accounts',
      'subAdminsNoItems': 'No Assistants yet. Tap + to create one.',
      'subAdminCreate': 'Create Assistant',
      'subAdminEdit': 'Edit Assistant',
      'subAdminRemove': 'Remove Assistant',
      'subAdminAssignSpaces': 'Assign Spaces',
      'subAdminAssignedSpaces': 'Assigned Spaces',
      'subAdminNoSpaces': 'No spaces assigned',
      'subAdminNameLabel': 'Name',
      'subAdminNameHint': 'Full name',
      'subAdminPasswordHint': 'Min 6 characters',
      'subAdminFillAll': 'Please fill all fields',
      // Booking Requests
      'adminBookingRequests': 'Booking Requests',
      'adminBookingRequestsSubtitle': 'Manage booking requests',
      'adminTabPending': 'Pending',
      'adminTabApproved': 'Approved',
      'adminTabAwaitingPayment': 'Awaiting payment',
      'adminTabAwaitingConfirmation': 'Awaiting confirmation',
      'adminTabBooked': 'Booked',
      'adminTabCanceled': 'Canceled',
      'adminTabPayReview': 'Pay Review',
      // Booking Details
      'adminBookingDetails': 'Booking Details',
      'adminCustomerInfo': 'Customer Information',
      'adminBookingInfo': 'Booking Information',
      'adminCancelBooking': 'Cancel Booking',
      'adminCancelReason': 'Please provide a reason for cancellation',
      'adminCancelReasonHint': 'Enter cancellation reason...',
      'adminConfirmCancel': 'Confirm Cancel',
      'adminConfirmBooking': 'Confirm Booking',
      'adminField': 'Field',
      'adminDetailsCol': 'Details',
      'adminKvSpace': 'Space',
      'adminKvAddress': 'Address',
      'adminKvDate': 'Date',
      'adminKvTime': 'Time',
      'adminKvDuration': 'Duration',
      'adminKvPlan': 'Plan',
      'adminKvPrice': 'Price',
      'adminKvTotal': 'Total',
      // My Spaces
      'adminMySpaces': 'My Spaces',
      'adminMySpacesSubtitle': 'Manage your listed spaces',
      'adminDeleteSpace': 'Delete Space',
      'adminDeleteSpaceConfirm': 'Are you sure you want to delete this space? This action cannot be undone.',
      // Add/Edit Space
      'adminAddSpace': 'Add Space',
      'adminEditSpace': 'Edit Space',
      'adminUpdateSpace': 'Update Space',
      'adminUpdateSpaceInfo': 'Update your space info',
      'adminSpaceName': 'Name',
      'adminSpaceNameHint': 'Space name',
      'adminAddressLabel': 'Address (text)',
      'adminAddressHint': 'e.g. 12 King St, Downtown',
      'adminTotalSeats': 'Total Seats',
      'adminSeatsHint': 'e.g. 20',
      'adminSeats': 'seats',
      'full': 'Full',
      'adminSpaceAdmin': 'Space Admin',
      'adminAssignSubAdmin': 'Assign Sub Admin',
      'adminSelectSubAdmin': 'Select sub admin (optional)',
      'adminFailedLoad': 'Failed to load space',
      'adminStep': 'Step',
      'adminOf': 'of',
      'adminStepBasicInfo': 'Basic information',
      'adminStepMediaPricing': 'Media, pricing & payment',
      'adminStepAvailability': 'Space availability',
      'adminStepDetailsPolicies': 'Amenities & policies',
      'adminSpaceSavedSuccess': 'Space saved successfully',
      // Payment Review
      'adminPaymentReview': 'Payment Review',
      'adminPaymentReviewSubtitle': 'Verify incoming payments',
      'adminNoPaymentsPending': 'No payments pending review',
      'adminUnderReview': 'Under Review',
      'adminPaymentUser': 'User',
      'adminPaymentAmount': 'Amount',
      'adminPaymentMethod': 'Method',
      'adminPaymentPaidAt': 'Paid at',
      'adminPaymentReceipt': 'Payment Receipt',
      'adminViewReceipt': 'View Receipt',
      'adminNoReceipt': 'No receipt uploaded',
      // Payment Methods (add/edit space)
      'adminPaymentMethodsTitle': 'Available Payment Methods',
      'adminPaymentMethodsSubtitle': 'Select methods and enter account details for each',
      'adminPaymentAccountDetails': 'Account Details',
      'adminPaymentAccountDetailsHint': 'Account number, IBAN, owner name...',
      'adminSelectPaymentMethod': 'Select payment method...',
      'adminAddPaymentMethod': 'Add',
      'adminPaymentAccountName': 'Account Holder Name',
      'adminPaymentAccountNameHint': 'Full name of account owner',
      'adminPaymentPhone': 'Phone Number',
      'adminPaymentName': 'Wallet owner name',
      'adminPaymentCardNote': 'Card payment is processed through the space\'s point-of-sale terminal upon arrival.',
      // Payment page (user side)
      'paymentMethodTitle': 'Payment Method',
      'paymentMethodDetails': 'Transfer Details',
      'paymentUploadReceipt': 'Upload Payment Receipt',
      'paymentOrEnterTransferData': 'or enter payment data',
      'paymentPayerAccountName': 'Payer account name',
      'paymentPayerAccountNameHint': 'Name used for transfer',
      'paymentTransferTime': 'Transfer time',
      'paymentReferenceNumber': 'Reference number',
      'paymentReferenceNumberHint': 'Bank transaction reference',
      'paymentReceiptUploaded': 'Receipt Uploaded',
      'paymentChangeReceipt': 'Change Receipt',
      'paymentCompleteBtn': 'Complete Payment',
      'paymentReceiptRequired': 'Please upload the payment receipt first',
      'paymentSelectMethodRequired': 'Please select a payment method',
      'paymentNoMethods': 'No payment methods available for this space',
      'paymentCardDetails': 'Card Details',
      'paymentCardNumber': 'Card Number',
      'paymentCardExpiry': 'Expiry Date',
      'paymentCardCvv': 'CVV',
      'paymentCardHolder': 'Card Holder Name',
      'cancelInfoTitle': 'Cancellation details',
      'cancelledByLabel': 'Cancelled by',
      'cancelReasonLabel': 'Reason',
      'cancelledAtLabel': 'Cancelled at',
      'cancellationStageLabel': 'Cancellation stage',
      'cancelReasonAddNew': 'Add new reason',
      'cancelDescriptionRequired': 'Cancellation description (required)',
      'cancelDescriptionOptional': 'Cancellation description (optional)',
      'cancelFeeWarning': 'Cancellation fees may apply by the space. Submit a complaint to request full refund.',
      'cancelReasonPlanChanged': 'Change of plans',
      'cancelReasonFoundOther': 'Found another space',
      'cancelReasonHighPrice': 'Price is high',
      'cancelReasonPaymentIssue': 'Payment issue',
      'cancelReasonTimeNotSuitable': 'Time is not suitable',
      'cancelReasonDetailsWrong': 'Booking details are incorrect',
      'cancelReasonDifferentLocation': 'Need different location',
      'cancelReasonMoreSeats': 'Need more seats',
      'cancelReasonFewerSeats': 'Need fewer seats',
      'cancelReasonEmergency': 'Emergency',
      'cancelReasonPolicyIssue': 'Space policy issue',
      'cancelReasonOther': 'Other',
      'cancelReasonNoAvailability': 'No availability',
      'cancelReasonMaintenance': 'Maintenance issue',
      'cancelReasonPricingConflict': 'Pricing conflict',
      'cancelReasonDuplicate': 'Duplicate booking',
      'cancelReasonClosed': 'Operational closure',
      'cancelReasonInsufficientDetails': 'Insufficient booking details',
      'cancelReasonSecurity': 'Security concern',
      // Settings
      'adminSettings': 'Settings',
      'adminAnalytics': 'Analytics',
      'adminPerformance': 'Performance',
      'adminPerformanceSubtitle': 'KPIs & weekly bookings',
      'adminTopSpaces': 'Top Spaces',
      'adminTopSpacesSubtitle': 'Top performing + export',
      'adminAdminActions': 'Admin actions',
      'adminViewRequestsSubtitle': 'Pending/approved/canceled',
      'adminManageCalendarSubtitle': 'Closures & special hours',
      'adminOffersManagement': 'Offers Management',
      'adminOffersManagementSubtitle': 'Discounts & packages',
      'adminReviewsReports': 'Reviews & Reports',
      'adminReviewsReportsSubtitle': 'Moderation & replies',
      'adminAccount': 'Account',
      'adminLogout': 'Logout',
      'adminLogoutSubtitle': 'Sign out of admin account',
      // Users
      'adminUsersTitle': 'Users',
      'adminUsersSubtitle': 'Search and manage users',
      'adminSearchUsers': 'Search users...',
      'adminFilterAll': 'All',
      'adminFilterNew': 'New',
      'adminFilterFlagged': 'Flagged',
      'apple': 'Apple login coming soon',
      'enterEmail': 'Enter your email and we will send you instructions.',
      'forgotPassword': 'Forgot Password',
      // Add Request Space
      'joinMsahtak': 'Join Msahtak spaces ,Start Journey Now',
      'addSpace': 'Add Space',
      'spaceRequestNote':
          'We will contact you to complete your space addition request through Msahtak team',
      'spaceName': 'Space Name',
      'description': 'Description',
      'phone': 'Phone Number',
      'whatsapp': 'WhatsApp Number',
      'contactName': 'Contact Name',
      'pricePD': 'Price per Day',
      'capacity': 'Capacity',
      'workingHours': 'Working Hours',
      'submit': 'Submit',
      'required': 'Required',
      'invalidNumber': 'Invalid number',
      'invalidPhone': 'Invalid phone number',
      'requestSuccess': 'Request sent successfully',
      'requestSuccessFull':
          'Your request has been sent successfully. We will contact you soon.',

      // Request Booking
      'requestBookingTitle': 'Request Booking',
      'purpose': 'Purpose',
      'selectPurpose': 'Select purpose',
      'startDate': 'Start Date',
      'selectDate': 'Select Date',
      'duration': 'Duration',
      'total': 'Total',
      'weeklyCheaper': 'Weekly plan is cheaper for you',
      'switch': 'Switch',
      'offerOptional': 'Offer (optional)',
      'chooseOffer': 'Choose an offer or skip',
      'weeklyPlan': 'Weekly plan',
      'monthlyPlan': 'Monthly plan',
      'promo': 'Promo',
      'addonsOptional': 'Add-ons (optional)',
      'priceSummary': 'Price summary',
      'sendBookingRequest': 'Send Request Booking',
      'requestBookingCta': 'Request Booking',
      'savedToFavorites': 'Saved to favorites',
      'removedFromFavorites': 'Removed from favorites',
      'openInMaps': 'Open in maps',
      'copyLocation': 'Copy location',
      'bookingRequirementsTitle': 'Complete your booking requirements',
      'bookingRequirementsSubtitle': 'Before booking, please make sure your phone number is added and your email is verified.',
      'bookingPhoneHint': 'Enter your phone number',
      'bookingEmailLabel': 'Account email',
      'bookingEmailVerified': 'Email is verified',
      'bookingEmailNotVerified': 'Email is not verified',
      'bookingSendVerificationBtn': 'Verify email',
      'bookingRefreshVerificationBtn': 'I verified, check again',
      'bookingContinueToRequestBtn': 'Continue to request',
      'bookingVerifyEmailHelp': 'After pressing verify, check your inbox and spam/junk folder.',
      'bookingVerifyEmailSent': 'Verification email sent to {email}. Check inbox and spam/junk.',
      'bookingLoginRequired': 'You need to be logged in to book.',

      // Pending
      'pendingApprovalTitle': 'Pending booking approval',
      'requestSent': 'Request sent successfully',
      'underReview': 'Your booking request is under review',
      'viewBookingStatus': 'View booking status',
      'goHome': 'Go to Home',
      "policies": "Policies",
      'ai': 'AI',
      // Status Page
      'paymentSubmitted': 'Payment submitted. Awaiting admin confirmation.',
      'bookingConfirmed': 'Booking confirmed! See you there.',
      'paymentExpired': 'Payment deadline expired. Booking was cancelled.',
      'paymentRejectedLabel': 'Payment Rejected',
      'activeStatusLabel': 'Active',
      'completedStatusLabel': 'Completed',
      'paymentRejectedMessage': 'Payment rejected by space owner.',
      'bookingActiveMessage': 'Booking is currently active.',
      'bookingCompletedMessage': 'Booking completed. Thank you!',
      'reportIssue': 'Report issue',
      'reportIssueTitle': 'Report issue',
      'reportIssueLoginRequired': 'You need to be logged in to submit an issue.',
      'reportIssueSubmitted': 'Issue submitted successfully. Support team was notified.',
      'reportIssueFailed': 'Failed to submit issue, please try again.',
      'downloadReceipt': 'Download Receipt',
      'receiptUnavailable': 'Receipt is not available yet.',
      'submitComplaint': 'Submit Complaint',
      'paymentTransferTimeHint': 'Tap to select date & time',
      'issueReason': 'Issue reason',
      'customReason': 'Custom reason',
      'issueDetails': 'Issue details',
      'submitIssue': 'Submit issue',
      'submitting': 'Submitting...',
      'pleaseEnterCustomReason': 'Please enter custom reason',
      'issueDescriptionMin': 'Please add at least 10 characters',
      'newIssueReportedTitle': 'New issue reported',
      'spaceLabel': 'Space',
      'bookingIdLabelShort': 'Booking ID',
      'currentStatusLabel': 'Current status',
      'issueReasonPaymentRefMismatch': 'Payment reference mismatch',
      'issueReasonReceiptUnclear': 'Receipt image is unclear',
      'issueReasonAccountNameMismatch': 'Account holder name mismatch',
      'issueReasonRejectedByMistake': 'Space owner rejected by mistake',
      'issueReasonOther': 'Other',
      'timelineProgressTitle': 'Progress',
      'timelinePaymentRejectedTitle': 'Payment rejected',
      'timelinePaymentRejectedSub': 'Please review note or report issue',
      'timelineActiveTitle': 'Active',
      'timelineActiveSub': 'Booking is currently active',
      'timelineCompletedTitle': 'Completed',
      'timelineCompletedSub': 'Booking ends automatically',
      'timelineWasActiveSub': 'Booking was active',
      'timelineCompletedDoneSub': 'Booking is completed',
      'timelineRequestSentTitle': 'Request sent',
      'timelineRequestSentSub': 'We received your request',
      'timelineUnderReviewTitle': 'Under review',
      'timelineReviewingSub': 'The space is reviewing your request',
      'timelineApprovedTitle': 'Approved',
      'timelineProceedPaymentSub': 'Proceed to payment',
      'timelineWaitingReviewSub': 'Waiting for review',
      'timelineReviewCompletedSub': 'Review completed',
      'timelineApprovedPayNowTitle': 'Approved - Pay now',
      'timelineCompletePaymentSub': 'Complete payment to continue',
      'timelinePaymentReviewTitle': 'Payment review',
      'timelinePaymentOwnerReviewSub': 'Payment will be reviewed by space owner',
      'timelineConfirmedTitle': 'Confirmed',
      'timelineConfirmedSub': 'Booking confirmed',
      'timelinePaymentSubmittedTitle': 'Payment submitted',
      'timelinePaymentSubmittedSub': 'Payment received',
      'timelinePaymentVerifyingSub': 'Payment is being verified',
      'timelinePaymentWasSubmittedSub': 'Payment was submitted',
      'timelinePaymentTitle': 'Payment',
      'timelinePaymentVerifiedSub': 'Payment verified',
      'timelineActiveStartsSub': 'Booking starts on schedule',
      'timelineExpiredTitle': 'Expired',
      'timelineExpiredSub': 'Payment deadline passed',
      'timelineCancelledTitle': 'Cancelled',
      'timelineCancelledSub': 'Booking was cancelled',
      'timelineRejectedTitle': 'Rejected',
      'timelineRejectedSub': 'Booking request was rejected',
      'payWithin': 'Pay within:',
      'paymentDeadlineExpired': 'Payment deadline expired',

      // Badge
      'pending': 'Pending',
      'underReviewStatus': 'Under Review',
      'approvedPay': 'Approved - Pay Now',
      'paymentReview': 'Payment Review',
      'confirmed': 'Confirmed',
      'rejected': 'Rejected',
      'cancelled': 'Cancelled',
      'expired': 'Expired',
      'loading': 'Loading...',
      'addNewSpace': 'Add New Space',
      'adminDashboard': 'Admin Dashboard',
      'manageSpaces': 'Manage your coworking spaces',
      'weeklyBookings': 'Weekly Bookings',
      'topSpaces': 'Top Performing Spaces',
      'exportReport': 'Export Report',
      'bookings': 'Bookings',
      'revenue': 'Revenue',
      'monthView': 'Month View',
      'calendarMonthly': 'Calendar (monthly)',
      'closeDay': 'Close the day',
      'specialHours': 'Special hours',
      'amenities': 'Amenities',
      'add': 'Add',
      'noAmenities': 'No amenities yet',
      'addAmenity': 'Add Amenity',
      'images': 'Images',
      'uploadFailed': 'Upload failed',
      'locationLatLng': 'Location (Lat/Lng)',
      'pick': 'Pick',
      'basePrice': 'Base Price',
      'day': 'day',
      'week': 'week',
      'month': 'month',
      'closed': 'Closed',
      'visibility': 'Visibility',
      'offerCreated': 'Offer created successfully',
      'fixedPrice': 'Fixed Price',
      'discount': 'Discount %',
      'packageMonths': 'Package (Months)',
      'bonus': 'Bonus',
      'validUntil': 'Valid until',
      'selectPeriod': 'Select Period',
      'selectStatus': 'Select Status',
      'reviewsReports': 'Reviews & Reports',
      'manageFeedback': 'Manage feedback and issues',
      'reply': 'Reply',
      'hide': 'Hide',

      'addNote': 'Add Note',
      'bookingHistory': 'Booking History',
      'todaysBookings': "Today's Bookings",
      'todaysOffers': "Today's Offers",
      'dontMissEssentials': "Don't miss essentials.",
      'noActiveBookings': "No active bookings",
      'notLoggedIn': "Not logged in",
      'error': "Error",
      'confirm': "Confirm",
      'yesCancel': "Yes, Cancel",
      'no': "No",
      'cancelBooking': "Cancel Booking",
      'areYouSureCancelBooking':
          "Are you sure you want to cancel this booking?",
      'bookingId': "Booking ID",
      'amountPaid': "Amount Paid",
      'date': "Date",
      'statusPaymentReview': "Payment Under Review",
      'invoice': "Invoice",
      'downloadInvoice': "Download Invoice (PDF)",
      'backToHome': "Back to Home",
      'paymentDone': "Payment done",
      'awaitingAdmin': "Awaiting admin confirmation. You will be notified.",
      'spaceDetails': "Space Details",
      'aboutApp': "About Mashtak",
      'selectLocation': "Pick Location",
      'confirmLocation': "Confirm",
      'continueBooking': "Continue to Booking",
      'fitScore': "Fit Score",
      'whyThisMatch': "Why this matches:",
      'headsUp': "Heads-up",
      'deal': "Deal",
      'perDay': "/day",
      'bookingSummary': "Booking Summary",
      'noOffersAvailable': "No offers available",
      'validUntilLabel': "Valid until: ",
      'yourReply': "Your Reply:",
      'reason': "Reason:",
      'internalRating': "Internal Rating",
      'noShow': "No-show",
    },
    'ar': {
      // ── Auth ──
      'login': 'تسجيل الدخول',
      'signUp': 'إنشاء حساب',
      'email': 'البريد الإلكتروني',
      'password': 'كلمة المرور',
      'confirmPassword': 'تأكيد كلمة المرور',
      'fullName': 'الاسم الكامل',
      'forgetPassword': 'نسيت كلمة المرور؟',
      'dontHaveAccount': 'ليس لديك حساب؟ ',
      'youHaveAccount': 'لديك حساب؟ ',
      'or': 'أو',
      'english': 'الإنجليزية',
      'arabic': 'العربية',
      'pleaseWait': 'يرجى الانتظار...',
      'pleaseFillAllFields': 'يرجى تعبئة جميع الحقول',
      'passwordsDoNotMatch': 'كلمات المرور غير متطابقة',
      'passwordLength': 'يجب أن تكون كلمة المرور 6 أحرف على الأقل',
      'accountCreated': 'تم إنشاء الحساب بنجاح!',
      'passwordResetTitle': 'إعادة تعيين كلمة المرور',
      'passwordResetBody':
          'تم ارسال بريد الكتروني الى عنوان بريدك.\nقم بتفقد بريدك ومتابعة الاوامر من هناك.',
      'ok': 'حسنًا',
      'send': 'إرسال',
      'backToLogin': 'العودة لتسجيل الدخول',
      // ── Onboarding common ──
      'skip': 'تخطي',
      'next': 'التالي',
      'goToHome': 'انتقل للرئيسية',
      // ── Onboarding Step 1 ──
      'findPerfectWorkspace': 'ابحث عن مساحة عملك المثالية',
      'bookStudySpaces':
          'احجز مساحات عمل ودراسة بأسعار واضحة، رؤى حقيقية، وخطط مرنة.',
      'clearInfoBeforeBook': 'معلومات واضحة قبل الحجز',
      'clearInfoSubtitle': 'السعر، التقييم، جودة الإنترنت، ومستوى الضوضاء.',
      'whyMashtak': 'لماذا مساحتك',
      'bookWithConfidence': 'احجز بثقة',
      'bookWithConfidenceSubtitle': 'يتم الموافقة على الطلبات قبل الدفع.',
      'smartSuggestions': 'اقتراحات ذكية',
      'smartSuggestionsSubtitle': 'نرشح لك أفضل الأماكن حسب هدفك.',
      'whatAreYouBookingFor': 'ما الهدف من الحجز؟',
      'selectAllThatApply': 'اختر ما يناسبك وسنرشح لك الأفضل.',
      'mainPurpose': 'الغرض الرئيسي',
      'selectMultiple': 'اختر متعدد',
      'whatMattersMost': 'ما الأهم لك؟',
      'whatMattersOptional': 'اختياري — يساعدنا في ترتيب النتائج.',
      'youllSeeInsightsLike': 'ستشاهد رؤى مثل',
      'insightBestStudy': 'الأفضل للدراسة',
      'insightQuietInternet': 'هادئ + إنترنت قوي',
      'insightWeeklySaves': 'الأسبوعي يوفر أكثر',
      'aiWillUseYourChoices': 'الذكاء الاصطناعي سيستخدم اختياراتك',
      'aiSubtitle': 'اقتراحات أذكى + ملخصات مراجعات\n(ليس روبوتًا للدردشة).',
      'aiFootnote': 'يمكنك تغيير هذه الإعدادات لاحقًا في الإعدادات.',
      // ── Onboarding Step 2 — Purposes ──
      'purposeStudy': 'دراسة',
      'purposeDeepFocus': 'تركيز عميق',
      'purposeMeetings': 'اجتماعات',
      'purposeTeamWork': 'عمل جماعي',
      'purposeCallsInterviews': 'مكالمات / مقابلات',
      'purposeCreative': 'إبداعي',
      // ── Onboarding Step 2 — Matters ──
      'matterQuiet': 'هادئ',
      'matterFastWifi': 'واي فاي سريع',
      'matterBudgetFriendly': 'موفر للميزانية',
      // ── Onboarding Step 3 ──
      'stayUpdated': 'ابقَ على اطلاع',
      'chooseAlerts': 'اختر التنبيهات التي تريدها.\nيمكنك تغييرها في أي وقت.',
      'bookingAlerts': 'تنبيهات الحجز',
      'bookingApproved': 'تم الموافقة على الحجز',
      'bookingApprovedSubtitle': 'عندما تؤكد مساحة طلبك.',
      'bookingRejected': 'تم رفض الحجز',
      'bookingRejectedSubtitle': 'حتى تتمكن من اختيار خيار آخر بسرعة.',
      'reminderBeforeBooking': 'تذكير قبل الحجز',
      'reminderBeforeBookingSubtitle': 'تذكير سريع قبل وقت حجزك.',
      'reminderTiming': 'وقت التذكير',
      'optionalLabel': 'اختياري',
      'notificationsHelp': 'الإشعارات تساعدك تتابع حجوزاتك',
      'notificationsSubtitle': 'تصلك التحديثات فوراً',
      'notificationsFootnote': 'يمكنك متابعة الحالة أيضاً من صفحة الحجوزات',
      'timing30min': '30 دقيقة',
      'timing1hour': 'ساعة واحدة',
      'timingSameDay': 'نفس اليوم (9 ص)',
      // ── Bottom Navigation ──
      'navHome': 'الرئيسية',
      'navBookings': 'الحجوزات',
      'navProfile': 'الملف الشخصي',
      'navSettings': 'الإعدادات',
      // ── Home Tab ──
      'homeTitle': 'الرئيسية',
      'searchHint': 'ابحث...',
      'aiConcierge': 'المساعد الذكي',
      'catNearly': 'قريب',
      'catNewSuggestion': 'اقتراح جديد',
      'catPrivateOffice': 'مكتب خاص',
      'forYou': 'مناسب لك',
      'noSpacesYet': 'لا توجد مساحات حالياً',
      'insightsSection': 'اقتراحات',
      'noInsightsYet': 'لا توجد بيانات بعد',
      'view': 'عرض',
      // ── Home Insights ──
      'insBestForYou': 'الأنسب لك',
      'insBestForYouSub': 'ابحث عن المساحة التي تناسب هدفك.',
      'insExclusiveDeals': 'عروض حصرية',
      'insExclusiveDealsSub': 'عروض حصرية على أفضل المساحات.',
      'insWeeklyPlan': 'الخطة الأسبوعية',
      'insWeeklyPlanSub': 'اكتشف مركز إنتاجيتك.',
      'insMeetingChecklist': 'قائمة تحضير الاجتماع',
      'insMeetingChecklistSub': 'لا تفوتك الأساسيات.',
      // ── Offers Page ──
      'offersPageTitle': 'العروض',
      'offersTopDeals': 'أفضل الصفقات',
      'offersEmpty': 'لا توجد عروض متاحة الآن.',
      // ── Bookings Tab ──
      'upcomingBookings': 'حجوزاتك القادمة',
      'pastBookings': 'الحجوزات السابقة',
      'cancelledBookings': 'الحجوزات الملغاة',
      'awaitingConfirmationTab': 'بانتظار التأكيد',
      'confirmedBookingsTab': 'تم التأكيد',
      'noBookingsYet': 'لا توجد حجوزات بعد',
      'bookingLoadErrorPrefix': 'خطأ:',
      'cancel': 'إلغاء',
      'rebook': 'إعادة الحجز',
      'manageBooking': 'إدارة الحجز',
      'bookingStatusUpcoming': 'قادم',
      'bookingStatusCompleted': 'مكتمل',
      'bookingStatusCancelled': 'ملغي',
      'bookingStatusAwaitingConfirmation': 'بانتظار التأكيد',
      'bookingStatusConfirmed': 'مؤكد',
      'bookingIdLabel': 'رقم الحجز:',
      'pricePerDay': '/يوم',
      'bookingInfoLabel': 'معلومات الحجز',
      'bookingDateLabel': 'التاريخ',
      'bookingTimeLabel': 'الوقت',
      'bookingNotesLabel': 'ملاحظات',
      'bookingTotalLabel': 'الإجمالي',
      'bookingDetailsTitle': 'تفاصيل الحجز',
      'bookingDetailsErrorPrefix': 'خطأ:',
      'bookingDetailsActionPlaceholder': 'إجراء (تجريبي)',
      // ── Profile Tab ──
      'profileTitle': 'الملف الشخصي',
      'saved': 'المحفوظات',
      'reviews': 'التقييمات',
      'personalInfo': 'المعلومات الشخصية',
      'yourUsage': 'استخدامك',
      'paymentsReceipts': 'الدفع والفواتير',
      'paymentDetails': 'تفاصيل الدفع',
      'reviewsRatings': 'التقييمات',
      'savedSpaces': 'المساحات المحفوظة',
      'logOut': 'تسجيل الخروج',
      // ── Settings Tab ──
      'settingsTitle': 'الإعدادات',
      'preferences': 'التفضيلات',
      'workspacePreferences': 'تفضيلات المساحة',
      'workspacePreferencesSub': 'دراسة، عمل، اجتماعات',
      'location': 'الموقع',
      'locationSub': 'البحث القريب وخريطة',
      'notifications': 'الإشعارات',
      'notificationsSub': 'الحجوزات والعروض',
      'appLanguage': 'اللغة',
      'appLanguageSub': 'العربية / الإنجليزية',
      'chooseLanguage': 'اختر اللغة',
      'close': 'إغلاق',
      'support': 'الدعم',
      'helpSupport': 'المساعدة والدعم',
      'helpSupportSub': 'الأسئلة الشائعة، اتصل بنا',
      'aboutMashtak': 'عن مساحتك',
      'aboutMashatakSub': 'الإصدار، الشروط، الخصوصية',
      'retry': 'إعادة المحاولة',
      'noInternetTitle': 'لا يوجد اتصال بالإنترنت',
      // ── Notifications Page ──
      'notificationsPageTitle': 'الإشعارات',
      'notificationsPageHeader': 'تحديثات لك',
      'notificationsPageSubtitle': 'حالة الحجز، تذكيرات، ونصائح الخطة الذكية.',
      'notifGroupToday': 'اليوم',
      'notifGroupEarlier': 'السابق',
      // ── Notification Item Content ──
      'notifItemTitleApproved': 'تمت الموافقة على حجزك! 🎉',
      'notifItemSubApproved': 'تم تأكيد حجزك بنجاح.',
      'notifItemTitleRejected': 'تم رفض الحجز',
      'notifItemSubRejected': 'للأسف لم يتم قبول طلبك. جرب مكاناً آخر.',
      'notifItemTitleReminder': 'تذكير بالحجز ⏰',
      'notifItemSubReminder': 'جلستك ستبدأ قريباً. استعد!',
      'notifItemTitleOffer': 'عرض أسبوعي جديد 🔥',
      'notifItemSubOffer': 'وفّر أكثر مع الباقة الأسبوعية. أماكن محدودة!',
      // ── Notification Settings Page ──
      'notifSettingsTitle': 'إعدادات الإشعارات',
      'notifSettingsStayInControl': 'ابقَ في التحكم',
      'notifSettingsChooseUpdates': 'اختر التحديثات التي تريد استلامها.',
      'notifSettingsBookingReminder': 'تذكير الحجز',
      'notifSettingsReminderSub': 'تذكير قبل وقت حجزك.',
      'notifSettingsOffersPlans': 'العروض والخطط',
      'notifSettingsOfferSuggestion': 'اقتراح عرض / خطة',
      'notifSettingsOfferSub': 'الخطة الأسبوعية قد توفر لك المال.',
      'save': 'حفظ',
      // ── Usage Page ──
      'usagePageTitle': 'استخدامك',
      'usageBasedOn': 'بناءً على آخر 30 يومًا',
      'usagePlanOptimizer': 'محسّن الخطة',
      'usageComparePlans': 'قارن الخطط',
      'usageRecommendation': 'التوصية',
      'usageApplyPlan': 'تطبيق الخطة',
      'usagePlanApplied': 'تم تطبيق الخطة بنجاح!',
      // ── Reviews Page ──
      'reviewsPageTitle': 'التقييمات والمراجعات',
      'save': 'حفظ',
      'weeklyPlanTitle': 'الخطة الأسبوعية',
      'weeklyPlanSaveMore': 'وفر أكثر مع الخطة الأسبوعية',
      'weeklyPlanActivate': 'تفعيل الخطة',
      'weeklyPlanActivated': 'تم تفعيل الخطة بنجاح!',
      'bookingStatusPageTitle': 'حالة الحجز',
      'bookingStatusHeader': 'طلب الحجز',
      'bookingStatusRefreshBtn': 'تحديث الحالة',
      'bookingStatusCancelBtn': 'إلغاء الطلب',
      'bookingStatusGoPaymentBtn': 'الذهاب للدفع',
      'notificationsPageSubtitle': 'حالة الحجز والتنبيهات والنصائح',
      'notifItemTitleApproved': 'تمت الموافقة على الحجز',
      'notifItemSubApproved': 'تم تأكيد حجزك',
      'notifItemTitleRejected': 'تم رفض الحجز',
      'notifItemSubRejected': 'لم يتم قبول الطلب، جرّب خيار آخر',
      'notifItemTitleReminder': 'تذكير بالحجز',
      'notifItemSubReminder': 'موعدك قريب',
      'notifItemTitleOffer': 'عرض جديد',
      'notifItemSubOffer': 'وفر أكثر مع العروض',
      'notifSettingsTitle': 'إعدادات الإشعارات',
      'notifSettingsStayInControl': 'تحكم بالإشعارات',
      'notifSettingsChooseUpdates': 'اختر ما تريد استلامه',
      'notifSettingsBookingReminder': 'تذكير الحجز',
      'notifSettingsReminderSub': 'قبل موعد الحجز',
      'notifSettingsOffersPlans': 'العروض والخطط',
      'notifSettingsOfferSuggestion': 'اقتراحات',
      'notifSettingsOfferSub': 'قد توفر لك المال',
      'usagePageTitle': 'استخدامك',
      'usageBasedOn': 'آخر 30 يوم',
      'usagePlanOptimizer': 'تحسين الخطة',
      'usageComparePlans': 'مقارنة الخطط',
      'usageRecommendation': 'توصية',
      'usageApplyPlan': 'تطبيق الخطة',
      'usagePlanApplied': 'تم التطبيق بنجاح',
      'reviewsPageTitle': 'التقييمات',
      'reviewsFilter': 'تصفية',
      'reviewsAll': 'الكل',
      'reviewsMyReviews': 'مراجعاتي',
      'reviewsMostRecent': 'الأحدث',
      'reviewsRecent': 'المراجعات الأخيرة',
      'reviewsTip': 'نصيحة: يمكنك تعديل مراجعاتك من صفحة المساحة',
      'reviewsOverall': 'الإجمالي',
      'reviewsBasedOn': 'بناءً على',
      'reviewsBasedOnSuffix': 'تقييم',
      // ── Weekly Plan Page ──
      'weeklyPlanTitle': 'الخطة الأسبوعية',
      'weeklyPlanSaveMore': 'وفّر أكثر مع الوصول الأسبوعي',
      'weeklyPlanSubtitle': 'الخيار الأفضل للزيارات المتكررة والعمل المركّز',
      'weeklyPlanWhatYouGet': 'ما الذي ستحصل عليه',
      'weeklyPlanActivate': 'تفعيل الخطة',
      'weeklyPlanActivated': 'تم تفعيل الخطة بنجاح!',
      // ── Booking Status Page ──
      'bookingStatusPageTitle': 'حالة الحجز',
      'bookingStatusHeader': 'طلب الحجز',
      'bookingStatusPullRefresh': 'اسحب للأسفل لتحديث الحالة',
      'bookingStatusApprovedBanner': 'تمت الموافقة على الحجز. تفضل بإتمام الدفع.',
      'bookingStatusRefreshBtn': 'تحديث الحالة',
      'bookingStatusCancelBtn': 'إلغاء الطلب',
      'bookingStatusGoPaymentBtn': 'الانتقال للدفع',
      'bookingStatusPaidMsg': 'تم الدفع بنجاح. يمكنك مراجعة تفاصيل الحجز من قائمة حجوزاتك.',
      // ── Booking Timeline ──
      'timelineProgress': 'التقدم',
      'timelineRequestSent': 'تم إرسال الطلب',
      'timelineRequestSentSub': 'استلمنا طلبك',
      'timelineUnderReview': 'قيد المراجعة',
      'timelineUnderReviewSub': 'جاري التحقق من التوفر',
      'timelineUnderReviewWaiting': 'بانتظار بدء المراجعة',
      'timelineUnderReviewCompleted': 'مكتمل',
      'timelineApproved': 'تمت الموافقة',
      'timelineApprovedSub': 'تفضل بإتمام الدفع',
      'timelinePaymentCompleted': 'تم الدفع',
      'timelineCancelled': 'ملغي',
      'timelineCancelledSub': 'الطلب ألغاه المستخدم',
      'timelineRejected': 'مرفوض',
      'timelineRejectedSub': 'تم رفض الطلب',
      // ── Booking Summary Card ──
      'summaryRequestId': 'رقم الطلب',
      'summaryStart': 'تاريخ البداية',
      'summaryDuration': 'المدة',
      'summaryPurpose': 'الغرض',
      'summaryOffer': 'العرض',
      'summaryTotal': 'الإجمالي',
      // ── Status Badges ──
      'statusPending': 'قيد الانتظار',
      'statusUnderReview': 'قيد المراجعة',
      'statusApproved': 'تمت الموافقة',
      'statusRejected': 'مرفوض',
      'statusCancelled': 'ملغي',
      'statusPaid': 'مدفوع',
      'statusLoading': 'جاري التحميل',
      // ── KPI Tiles ──
      'kpiTodayTitle': 'حجوزات اليوم',
      'kpiTodayDelta': 'حجز اليوم',
      'kpiPendingTitle': 'طلبات معلقة',
      'kpiNeedsReview': 'تحتاج مراجعة',
      'kpiAllClear': 'كل شيء واضح',
      'kpiSpacesTitle': 'المساحات النشطة',
      'kpiSpacesDelta': 'إجمالي المساحات',
      'kpiRevenueTitle': 'إيرادات الأسبوع',
      'kpiRevenueDelta': 'آخر 7 أيام',
      // ── Activity ──
      'activityRequested': 'طلب حجزاً في',
      'activityApproved': 'تمت الموافقة على حجزه في',
      'activityPayment': 'قدّم دفعة لـ',
      'activityConfirmed': 'أكّد الحجز في',
      'activityCancelled': 'ألغى الحجز في',
      'activityBooked': 'حجز',
      // ── Time Ago ──
      'timeJustNow': 'الآن',
      'timeMinAgo': 'دقيقة مضت',
      'timeHoursAgo': 'ساعة مضت',
      'timeDaysAgo': 'يوم مضت',
      // ── Map ──
      'mapShowAll': 'عرض الكل',
      'mapNearby': 'قريب',
      'mapNoResults': 'لا توجد نتائج في هذا النطاق.',
      'mapTitle': 'استكشف المساحات على الخريطة',
      // ── Admin ──
      'adminTabHome': 'الرئيسية',
      'adminTabBookings': 'الحجوزات',
      'adminTabUsers': 'المستخدمون',
      'adminTabSubAdmins': 'المساعدين',
      'adminTabSettings': 'الإعدادات',
      'adminDashboardTitle': 'لوحة التحكم',
      'adminDashboardSubtitle': 'إدارة مساحات العمل المشتركة',
      'adminSelectedSpace': 'المساحة المحددة',
      'adminSelectSpace': 'اختر مساحة',
      'adminRecentActivity': 'النشاط الأخير',
      'adminMore': 'المزيد',
      'adminNoRecentActivity': 'لا يوجد نشاط حديث',
      'adminQuickActions': 'إجراءات سريعة',
      'adminViewRequests': 'عرض الطلبات',
      'adminManageCalendar': 'إدارة التقويم',
      'adminCreateOffer': 'إنشاء عرض',
      'adminViewReviews': 'عرض التقييمات',
      'adminManageSubAdmins': 'إدارة المساعدين ',
      'adminManage': 'إدارة',
      'adminHide': 'إخفاء',
      'adminHidden': 'مخفي',
      'adminAvailable': 'متاح',
      'adminAvailability': 'الحالة',
      'adminImage': 'صورة',
      'adminDelete': 'حذف',
      'adminRetry': 'إعادة المحاولة',
      'adminBack': 'رجوع',
      'adminNone': 'لا أحد',
      'adminConfirm': 'تأكيد',
      'adminReject': 'رفض',
      'adminSaving': 'جاري الحفظ...',
      // Sub Admins
      'subAdminsTitle': 'المساعدين',
      'subAdminsSubtitle': 'إدارة حسابات المساعدين المقيدة',
      'subAdminsNoItems': 'لا يوجد مساعدين. اضغط + لإنشاء واحد.',
      'subAdminCreate': 'إنشاء مساعد',
      'subAdminEdit': 'تعديل المساعد',
      'subAdminRemove': 'إزالة المساعد',
      'subAdminAssignSpaces': 'تعيين المساحات',
      'subAdminAssignedSpaces': 'المساحات المعينة',
      'subAdminNoSpaces': 'لا توجد مساحات معينة',
      'subAdminNameLabel': 'الاسم',
      'subAdminNameHint': 'الاسم الكامل',
      'subAdminPasswordHint': 'لا يقل عن 6 أحرف',
      'subAdminFillAll': 'يرجى ملء جميع الحقول',
      // Booking Requests
      'adminBookingRequests': 'طلبات الحجز',
      'adminBookingRequestsSubtitle': 'إدارة طلبات الحجز',
      'adminTabPending': 'قيد الانتظار',
      'adminTabApproved': 'موافق عليه',
      'adminTabAwaitingPayment': 'قيد انتظار الدفع',
      'adminTabAwaitingConfirmation': 'قيد انتظار التأكيد',
      'adminTabBooked': 'تم الحجز',
      'adminTabCanceled': 'ملغي',
      'adminTabPayReview': 'مراجعة الدفع',
      // Booking Details
      'adminBookingDetails': 'تفاصيل الحجز',
      'adminCustomerInfo': 'معلومات العميل',
      'adminBookingInfo': 'معلومات الحجز',
      'adminCancelBooking': 'إلغاء الحجز',
      'adminCancelReason': 'يرجى تقديم سبب الإلغاء',
      'adminCancelReasonHint': 'أدخل سبب الإلغاء...',
      'adminConfirmCancel': 'تأكيد الإلغاء',
      'adminConfirmBooking': 'تأكيد الحجز',
      'adminField': 'الحقل',
      'adminDetailsCol': 'التفاصيل',
      'adminKvSpace': 'المساحة',
      'adminKvAddress': 'العنوان',
      'adminKvDate': 'التاريخ',
      'adminKvTime': 'الوقت',
      'adminKvDuration': 'المدة',
      'adminKvPlan': 'الباقة',
      'adminKvPrice': 'السعر',
      'adminKvTotal': 'الإجمالي',
      // My Spaces
      'adminMySpaces': 'مساحاتي',
      'adminMySpacesSubtitle': 'إدارة مساحاتك المدرجة',
      'adminDeleteSpace': 'حذف المساحة',
      'adminDeleteSpaceConfirm': 'هل أنت متأكد أنك تريد حذف هذه المساحة؟ لا يمكن التراجع عن هذا الإجراء.',
      // Add/Edit Space
      'adminAddSpace': 'إضافة مساحة',
      'adminEditSpace': 'تعديل مساحة',
      'adminUpdateSpace': 'تحديث المساحة',
      'adminUpdateSpaceInfo': 'تحديث البيانات',
      'adminSpaceName': 'اسم المساحة',
      'adminSpaceNameHint': 'اكتب الاسم',
      'adminAddressLabel': 'العنوان',
      'adminAddressHint': 'مثال: شارع الملك',
      'adminTotalSeats': 'عدد المقاعد',
      'adminSeatsHint': 'مثال: 20',
      'adminSeats': 'مقاعد',
      'full': 'ممتلئ',
      'adminSpaceAdmin': 'مشرف المساحة',
      'adminAssignSubAdmin': 'تعيين مساعد',
      'adminSelectSubAdmin': 'اختر مساعد (اختياري)',
      'adminFailedLoad': 'فشل تحميل المساحة',
      'adminStep': 'الخطوة',
      'adminOf': 'من',
      'adminStepBasicInfo': 'المعلومات الأساسية',
      'adminStepMediaPricing': 'الصور والسعر والدفع',
      'adminStepAvailability': 'توافر المساحة',
      'adminStepDetailsPolicies': 'المميزات والسياسات',
      'adminSpaceSavedSuccess': 'تم حفظ المساحة بنجاح',
      // Payment Review
      'adminPaymentReview': 'مراجعة الدفع',
      'adminPaymentReviewSubtitle': 'التحقق من المدفوعات الواردة',
      'adminNoPaymentsPending': 'لا توجد مدفوعات بانتظار المراجعة',
      'adminUnderReview': 'قيد المراجعة',
      'adminPaymentUser': 'المستخدم',
      'adminPaymentAmount': 'المبلغ',
      'adminPaymentMethod': 'الطريقة',
      'adminPaymentPaidAt': 'تاريخ الدفع',
      'adminPaymentReceipt': 'إشعار الدفع',
      'adminViewReceipt': 'عرض الإشعار',
      'adminNoReceipt': 'لم يُرفع إشعار',
      // Payment Methods (add/edit space)
      'adminPaymentMethodsTitle': 'طرق الدفع المتاحة',
      'adminPaymentMethodsSubtitle': 'اختر الطرق وأدخل تفاصيل الحساب لكل طريقة',
      'adminPaymentAccountDetails': 'تفاصيل الحساب',
      'adminPaymentAccountDetailsHint': 'رقم الحساب، IBAN، اسم صاحب الحساب...',
      'adminSelectPaymentMethod': 'اختر طريقة الدفع...',
      'adminAddPaymentMethod': 'إضافة',
      'adminPaymentAccountName': 'اسم صاحب الحساب',
      'adminPaymentAccountNameHint': 'الاسم الكامل لصاحب الحساب',
      'adminPaymentPhone': 'رقم الهاتف',
      'adminPaymentName': 'اسم صاحب المحفظة',
      'adminPaymentCardNote': 'الدفع بالبطاقة يتم عبر جهاز نقطة البيع في المساحة عند الوصول.',
      // Payment page (user side)
      'paymentMethodTitle': 'طريقة الدفع',
      'paymentMethodDetails': 'تفاصيل التحويل',
      'paymentUploadReceipt': 'رفع إشعار الدفع',
      'paymentOrEnterTransferData': 'أو قم بإدخال بيانات الدفع',
      'paymentPayerAccountName': 'اسم صاحب الحساب',
      'paymentPayerAccountNameHint': 'الاسم المستخدم في عملية التحويل',
      'paymentTransferTime': 'وقت التحويل',
      'paymentReferenceNumber': 'الرقم المرجعي',
      'paymentReferenceNumberHint': 'رقم مرجع العملية البنكية',
      'paymentReceiptUploaded': 'تم رفع الإشعار',
      'paymentChangeReceipt': 'تغيير الإشعار',
      'paymentCompleteBtn': 'إتمام الدفع',
      'paymentReceiptRequired': 'يرجى رفع إشعار الدفع أولاً',
      'paymentSelectMethodRequired': 'يرجى اختيار طريقة الدفع',
      'paymentNoMethods': 'لا توجد طرق دفع لهذه المساحة',
      'paymentCardDetails': 'بيانات البطاقة',
      'paymentCardNumber': 'رقم البطاقة',
      'paymentCardExpiry': 'تاريخ الانتهاء',
      'paymentCardCvv': 'CVV',
      'paymentCardHolder': 'اسم صاحب البطاقة',
      // Settings
      'adminSettings': 'الإعدادات',
      'adminAnalytics': 'الإحصائيات',
      'adminPerformance': 'الأداء',
      'adminPerformanceSubtitle': 'مؤشرات الأداء والحجوزات الأسبوعية',
      'adminTopSpaces': 'أفضل المساحات',
      'adminTopSpacesSubtitle': 'الأفضل أداءً + تصدير',
      'adminAdminActions': 'إجراءات الإدارة',
      'adminViewRequestsSubtitle': 'قيد الانتظار / موافق / ملغي',
      'adminManageCalendarSubtitle': 'الإغلاقات وساعات خاصة',
      'adminOffersManagement': 'إدارة العروض',
      'adminOffersManagementSubtitle': 'الخصومات والباقات',
      'adminReviewsReports': 'التقييمات والتقارير',
      'adminReviewsReportsSubtitle': 'الإشراف والردود',
      'adminAccount': 'الحساب',
      'adminLogout': 'تسجيل الخروج',
      'adminLogoutSubtitle': 'تسجيل الخروج من حساب الأدمن',
      // Users
      'adminUsersTitle': 'المستخدمون',
      'adminUsersSubtitle': 'بحث وإدارة المستخدمين',
      'adminSearchUsers': 'بحث عن مستخدمين...',
      'adminFilterAll': 'الكل',
      'adminFilterNew': 'جديد',
      'adminFilterFlagged': 'مُبلغ عنه',
      'insBestForYou': 'الأفضل لك',
      'insBestForYouSub': 'اعثر على المساحة المناسبة لهدفك',
      'insExclusiveDeals': 'عروض حصرية',
      'insExclusiveDealsSub': 'أفضل العروض على المساحات',
      'insWeeklyPlan': 'الخطة الأسبوعية',
      'insMeetingChecklist': 'تجهيزات الاجتماع',
      'insMeetingChecklistSub': 'لا تنسَ الأساسيات للاجتماع',
      'enterEmail': 'أدخل بريدك الإلكتروني وسنرسل لك التعليمات',
      'forgotPassword': 'نسيت كلمة المرور',
      'adminFilterFlagged': 'مبلغ عنه',
      // Add Request Space
      'joinMsahtak': 'انضم إلى مساحات مساحتك، ابدأ رحلتك الآن',
      'addSpace': 'إضافة مساحة',
      'spaceRequestNote':
          'سيتم التواصل معك لمتابعة إضافة المساحة من قبل فريق منصة مساحتك',
      'spaceName': 'اسم المساحة',
      'description': 'الوصف',
      'phone': 'رقم الهاتف',
      'whatsapp': 'رقم الواتساب',
      'contactName': 'اسم المسؤول',
      'pricePD': 'السعر لليوم',
      'capacity': 'السعة',
      'workingHours': 'ساعات العمل',
      'submit': 'إرسال',
      'required': 'مطلوب',
      'invalidNumber': 'رقم غير صالح',
      'invalidPhone': 'رقم هاتف غير صالح',
      'requestSuccess': 'تم إرسال الطلب بنجاح',
      'requestSuccessFull': 'تم إرسال طلبك بنجاح، سيتم التواصل معك في أقرب وقت',
      // Request Booking
      'requestBookingTitle': 'طلب حجز',
      'purpose': 'الغرض',
      'selectPurpose': 'اختر الغرض',
      'startDate': 'تاريخ البداية',
      'selectDate': 'اختر التاريخ',
      'duration': 'المدة',
      'weeklyCheaper': 'الخطة الأسبوعية أوفر لك',
      'switch': 'تبديل',
      'offerOptional': 'العروض (اختياري)',
      'chooseOffer': 'اختر عرض أو تخطى',
      'weeklyPlan': 'خطة أسبوعية',
      'monthlyPlan': 'خطة شهرية',
      'promo': 'عرض خاص',
      'addonsOptional': 'إضافات (اختياري)',
      'priceSummary': 'ملخص السعر',
      'sendBookingRequest': 'إرسال طلب الحجز',
      'requestBookingCta': 'طلب حجز',
      'savedToFavorites': 'تم الحفظ في المفضلة',
      'removedFromFavorites': 'تمت الإزالة من المفضلة',
      'openInMaps': 'فتح في الخرائط',
      'copyLocation': 'نسخ الموقع',
      'bookingRequirementsTitle': 'استكمال متطلبات الحجز',
      'bookingRequirementsSubtitle': 'قبل المتابعة للحجز، يرجى إضافة رقم الهاتف والتأكد من توثيق البريد الإلكتروني.',
      'bookingPhoneHint': 'أدخل رقم الهاتف',
      'bookingEmailLabel': 'البريد الإلكتروني للحساب',
      'bookingEmailVerified': 'البريد الإلكتروني موثّق',
      'bookingEmailNotVerified': 'البريد الإلكتروني غير موثّق',
      'bookingSendVerificationBtn': 'تأكيد البريد الإلكتروني',
      'bookingRefreshVerificationBtn': 'تم التوثيق، تحقق مجددًا',
      'bookingContinueToRequestBtn': 'متابعة إلى طلب الحجز',
      'bookingVerifyEmailHelp': 'بعد الضغط على التأكيد، راجع البريد الوارد وكذلك مجلد السبام/العشوائي.',
      'bookingVerifyEmailSent': 'تم إرسال رسالة التوثيق إلى {email}. راجع البريد الوارد والسبام/العشوائي.',
      'bookingLoginRequired': 'يجب تسجيل الدخول للمتابعة إلى الحجز.',
      // Pending
      'pendingApprovalTitle': 'بانتظار الموافقة',
      'requestSent': 'تم إرسال الطلب بنجاح',
      'underReview': 'طلب الحجز قيد المراجعة',
      'viewBookingStatus': 'عرض حالة الحجز',
      'goHome': 'العودة للرئيسية',
      // Status Page
      'paymentSubmitted': 'تم إرسال الدفع، بانتظار تأكيد الإدارة',
      'bookingConfirmed': 'تم تأكيد الحجز! نراك قريباً',
      'paymentExpired': 'انتهت مهلة الدفع وتم إلغاء الحجز',
      'paymentRejectedLabel': 'تم رفض الدفع',
      'activeStatusLabel': 'ساري',
      'completedStatusLabel': 'مكتمل',
      'paymentRejectedMessage': 'تم رفض الدفع من صاحب المساحة.',
      'bookingActiveMessage': 'حجزك ساري حالياً.',
      'bookingCompletedMessage': 'تم إنهاء الحجز بنجاح، شكراً لك!',
      'reportIssue': 'إبلاغ مشكلة',
      'reportIssueTitle': 'إبلاغ مشكلة',
      'reportIssueLoginRequired': 'يجب تسجيل الدخول لإرسال البلاغ.',
      'reportIssueSubmitted': 'تم إرسال البلاغ بنجاح وتم إشعار الدعم.',
      'reportIssueFailed': 'تعذر إرسال البلاغ، حاول مرة أخرى.',
      'downloadReceipt': 'تنزيل الإيصال',
      'receiptUnavailable': 'الإيصال غير متاح بعد.',
      'submitComplaint': 'تقديم شكوى',
      'paymentTransferTimeHint': 'اضغط لاختيار التاريخ والوقت',
      'issueReason': 'سبب المشكلة',
      'customReason': 'سبب مخصص',
      'issueDetails': 'تفاصيل المشكلة',
      'submitIssue': 'إرسال البلاغ',
      'submitting': 'جارٍ الإرسال...',
      'pleaseEnterCustomReason': 'الرجاء إدخال السبب المخصص',
      'issueDescriptionMin': 'الرجاء إدخال 10 أحرف على الأقل',
      'newIssueReportedTitle': 'تم استلام بلاغ جديد',
      'spaceLabel': 'المساحة',
      'bookingIdLabelShort': 'رقم الحجز',
      'currentStatusLabel': 'الحالة الحالية',
      'issueReasonPaymentRefMismatch': 'عدم تطابق الرقم المرجعي',
      'issueReasonReceiptUnclear': 'صورة الإيصال غير واضحة',
      'issueReasonAccountNameMismatch': 'عدم تطابق اسم صاحب الحساب',
      'issueReasonRejectedByMistake': 'تم رفض الدفع بالخطأ',
      'issueReasonOther': 'سبب آخر',
      'timelineProgressTitle': 'تقدم الحالة',
      'timelinePaymentRejectedTitle': 'تم رفض الدفع',
      'timelinePaymentRejectedSub': 'راجع الملاحظة أو قدّم بلاغ مشكلة',
      'timelineActiveTitle': 'ساري',
      'timelineActiveSub': 'الحجز ساري حالياً',
      'timelineCompletedTitle': 'مكتمل',
      'timelineCompletedSub': 'سينتهي الحجز تلقائياً',
      'timelineWasActiveSub': 'كان الحجز سارياً',
      'timelineCompletedDoneSub': 'اكتمل الحجز',
      'timelineRequestSentTitle': 'تم إرسال الطلب',
      'timelineRequestSentSub': 'تم استلام طلبك بنجاح',
      'timelineUnderReviewTitle': 'قيد المراجعة',
      'timelineReviewingSub': 'صاحب المساحة يراجع الطلب',
      'timelineApprovedTitle': 'تمت الموافقة',
      'timelineProceedPaymentSub': 'تابع إلى الدفع',
      'timelineWaitingReviewSub': 'بانتظار بدء المراجعة',
      'timelineReviewCompletedSub': 'اكتملت المراجعة',
      'timelineApprovedPayNowTitle': 'تمت الموافقة - ادفع الآن',
      'timelineCompletePaymentSub': 'أكمل الدفع للمتابعة',
      'timelinePaymentReviewTitle': 'مراجعة الدفع',
      'timelinePaymentOwnerReviewSub': 'سيتم مراجعة الدفع من صاحب المساحة',
      'timelineConfirmedTitle': 'مؤكد',
      'timelineConfirmedSub': 'تم تأكيد الحجز',
      'timelinePaymentSubmittedTitle': 'تم إرسال الدفع',
      'timelinePaymentSubmittedSub': 'تم استلام الدفع',
      'timelinePaymentVerifyingSub': 'جاري التحقق من الدفع',
      'timelinePaymentWasSubmittedSub': 'تم إرسال الدفع',
      'timelinePaymentTitle': 'الدفع',
      'timelinePaymentVerifiedSub': 'تم التحقق من الدفع',
      'timelineActiveStartsSub': 'سيبدأ الحجز في الموعد المحدد',
      'timelineExpiredTitle': 'منتهي',
      'timelineExpiredSub': 'انتهت مهلة الدفع',
      'timelineCancelledTitle': 'ملغي',
      'timelineCancelledSub': 'تم إلغاء الحجز',
      'timelineRejectedTitle': 'مرفوض',
      'timelineRejectedSub': 'تم رفض طلب الحجز',
      'payWithin': 'ادفع خلال:',
      'paymentDeadlineExpired': 'انتهت مهلة الدفع',
      // Badge
      'pending': 'قيد الانتظار',
      'underReviewStatus': 'قيد المراجعة',
      'approvedPay': 'تمت الموافقة - ادفع الآن',
      'paymentReview': 'مراجعة الدفع',
      'confirmed': 'مؤكد',
      'rejected': 'مرفوض',
      'cancelled': 'ملغي',
      'expired': 'منتهي',
      'loading': 'جارٍ التحميل...',
      'addNewSpace': 'إضافة مساحة جديدة',
      'adminDashboard': 'لوحة التحكم',
      'manageSpaces': 'إدارة مساحات العمل المشتركة',
      'weeklyBookings': 'الحجوزات الأسبوعية',
      'topSpaces': 'أفضل المساحات',
      'exportReport': 'تصدير التقرير',
      'bookings': 'الحجوزات',
      'revenue': 'الإيرادات',
      'monthView': 'عرض شهري',
      'calendarMonthly': 'التقويم (شهري)',
      'closeDay': 'إغلاق اليوم',
      'specialHours': 'ساعات خاصة',
      'amenities': 'المرافق',
      'add': 'إضافة',
      'noAmenities': 'لا توجد مرافق بعد',
      'addAmenity': 'إضافة مرفق',
      'images': 'الصور',
      'uploadFailed': 'فشل الرفع',
      'locationLatLng': 'الموقع (خط العرض/الطول)',
      'pick': 'اختيار',
      'basePrice': 'السعر الأساسي',
      'day': 'يوم',
      'week': 'أسبوع',
      'month': 'شهر',
      'closed': 'مغلق',
      'visibility': 'الظهور',
      'offerCreated': 'تم إنشاء العرض بنجاح',
      'fixedPrice': 'سعر ثابت',
      'discount': 'نسبة الخصم',
      'packageMonths': 'باقة (أشهر)',
      'bonus': 'مكافأة',
      'validUntil': 'صالح حتى',
      'selectPeriod': 'اختر الفترة',
      'selectStatus': 'اختر الحالة',
      'reviewsReports': 'التقييمات والتقارير',
      'manageFeedback': 'إدارة التقييمات والمشاكل',
      'reply': 'رد',
      'hide': 'إخفاء',
      'msahtak':'مساحتك',
      'addNote': 'إضافة ملاحظة',
      'bookingHistory': 'سجل الحجوزات',
      'todaysBookings': "حجوزات اليوم",
      'todaysOffers': "عروض اليوم",
      'dontMissEssentials': "لا تفوت الأساسيات",
      'noActiveBookings': "لا يوجد حجوزات حالياً",
      'notLoggedIn': "لم يتم تسجيل الدخول",
      'error': "خطأ",
      'confirm': "تأكيد",
      'yesCancel': "نعم، إلغاء",
      'no': "لا",
      'cancelBooking': "إلغاء الحجز",
      'areYouSureCancelBooking': "هل أنت متأكد من إلغاء هذا الحجز؟",
      'bookingId': "رقم الحجز",
      'amountPaid': "المبلغ المدفوع",
      'date': "التاريخ",
      'statusPaymentReview': "قيد مراجعة الدفع",
      'invoice': "فاتورة",
      'downloadInvoice': "تحميل الفاتورة",
      'backToHome': "العودة للرئيسية",
      'paymentDone': "تم الدفع",
      'awaitingAdmin': "بانتظار تأكيد الإدارة",
      'spaceDetails': "تفاصيل المساحة",
      'aboutApp': "حول التطبيق",
      'selectLocation': "اختيار الموقع",
      'confirmLocation': "تأكيد",
      'aiConcierge': "المساعد الذكي",
      'continueBooking': "متابعة الحجز",
      'fitScore': "نسبة التطابق",
      'whyThisMatch': "لماذا هذا مناسب:",
      'headsUp': "تنبيه",
      'deal': "عرض",
      'perDay': "/يوم",
      'bookingSummary': "ملخص الحجز",
      'total': "الإجمالي",
      'noOffersAvailable': "لا توجد عروض",
      'validUntilLabel': "صالح حتى: ",
      'yourReply': "ردك:",
      'reason': "السبب:",
      'internalRating': "التقييم الداخلي",
      'noShow': "عدم الحضور",
      "policies": "سياسات",
      'ai':'ذكاء الاصطناعي'
    },
  };

  /// Static translator
  static String tr(String code, String key) {
    return translations[code]?[key] ?? key;
  }
}
